spacetelescope/romancal

romancal/datamodels/schemas/core.schema.yaml
romancal/datamodels/schemas/reference_files/referencefile.schema.yaml

Creating Datamodel Tree

---

romancal/datamodels/schemas/core.schema.yaml
romancal/datamodels/schemas/reference_files/flat.schema.yaml
romancal/datamodels/schemas/reference_files/referencefile.schema.yaml

Adding flat file schema.
Updated core & referencefile schemas with requested changes and tweaks to match sample data provided by @tddesjardins .

Datamodelinit

---

romancal/datamodels/flat.py
romancal/datamodels/open_impl.py
romancal/datamodels/referencefile.py
romancal/datamodels/schemas/core.schema.yaml

Added initial model support for flat files and reference files. Modified open_impl.py to open flat files.

Support for Opening Flat Files

---

MANIFEST.in
setup.py

Added __init__.py files so that schemas actually install.

install schemas

---

docs/roman/datamodels/attributes.rst
docs/roman/datamodels/metadata.rst
docs/roman/datamodels/models.rst
docs/roman/datamodels/new_model.rst
docs/roman/datamodels/structure.rst

These are initial versions of updated general docs for the roman data model. As some asdf-related details are not yet known, these files require further work, in some areas marked as TBD.

Updates for RCAL-48

---

docs/roman/flatfield/reference_files.rst

This is the initial version of the updated datamodels flat field docs.

Updates for RCAL-49

---

docs/roman/error_propagation/index.rst
docs/roman/error_propagation/main.rst

Error Propagation files needed for RTD build. The main.rst is a copy of the JWST version, so needs romanization

Additional files needed for RTD

---

romancal/datamodels/flat.py
romancal/datamodels/schemas/reference_files/flat.schema.yaml

This is to match INS files for Build 0.0.

Updated the DQ array in flat file support to uint.

---

README.md
docs/roman/datamodels/metadata.rst
docs/roman/datamodels/models.rst
docs/roman/datamodels/new_model.rst
docs/roman/datamodels/structure.rst
docs/roman/includes/standard_keywords.inc
docs/roman/introduction.rst
docs/roman/references_general/flat_reffile.inc
docs/roman/references_general/flat_selection.inc

RCAL-66 Remove CGI from flat selection and update documentation

---

romancal/datamodels/dark.py
romancal/datamodels/schemas/core.schema.yaml
romancal/datamodels/schemas/reference_files/dark.schema.yaml

Initial implementation of the DataModel and schema for dark current files.

Adding DarkModel & Schema

---

romancal/datamodels/schemas/reference_files/referencefile.schema.yaml

Added the REFTYPEs from the following document to the Reference File Schemas.
https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=SCSB&title=Roman+Reference+Files

Added REFTYPE keywords from Roman Documentation.

---

.github/workflows/roman_ci.yml
romancal/datamodels/core.py
romancal/datamodels/referencefile.py

Adding github action workflows to the Roman calibration repository.

Adding github actions for romancal.

---

romancal/flatfield/flat_field.py
romancal/flatfield/flat_field_step.py
romancal/flatfield/tests/test_flatfield.py
romancal/flatfield/tests/test_interpolate_flat.py
romancal/romancal/flatfield/flat_field.py
romancal/romancal/flatfield/tests/test_flatfield.py

This PR includes code assuming access to libraries that have not yet been installed for Roman (DQ, CRDS, handling of ERR arrays, etc).

First version of flat fielding code ( RCAL-60 )

---

romancal/flatfield/__init__.py

Add __init__.py

---

romancal/datamodels/models/image/image.py
romancal/datamodels/schemas/image_files/image.schema.yaml

Added data variable objects to the image schema. Commented out variance and pathloss correction schemas until they are implemented. 
One question for reviewers: do we still need the drizzle correction arrays?

Added variable objects to image schema.

---

setup.cfg

We released the changes that are needed in stdatamodels master.

Use stdatamodels 0.2.0

---

romancal/datamodels/__init__.py
romancal/datamodels/reference_files/gain.py
romancal/datamodels/schemas/reference_files/gain.schema.yaml
romancal/datamodels/schemas/reference_files/keyword_gainfact.schema.yaml

Gain and keyword schema and model. 
Init also updated to include dark model.

Gain Schema & Datamodel

---

romancal/datamodels/schemas/reference_files/readnoise.schema.yaml

Addresses reviewer comments on PRs 114 and 131.

Create Roman readnoise schema.

---

romancal/datamodels/__init__.py
romancal/datamodels/reference_files/readnoise.py

Create Roman ReadnoiseModel ( RCAL-78, see Github issue #90 )

Create Roman Readnoise model

---

README.md
romancal/datamodels/schemas/core.schema.yaml

The engineering filter is to be officially removed from the set of elements and replaced with F213.

Rcal-83 Update optical element ENG -> F213

---

romancal/stpipe/tests/test_core.py
setup.cfg

Adds more tests to crds_client.
Reolves RCAL-103/#144

RCAL-103 test_303

---

romancal/dark_current/__init__.py
romancal/dark_current/dark_current_step.py
romancal/dark_current/dark_sub.py

Convert JWST dark current subtraction step for WFI data

Convert JWST dark current step for Roman

---

romancal/dark_current/dark_current_step.py
romancal/step.py
romancal/stpipe/integration.py

Adding the dark current step to the list of entry points for the unit tests that will be added.

Adding dark current to the entry points.

---

CHANGES.rst
README.md
romancal/dark_current/dark_current_step.py
romancal/dark_current/dark_sub.py
romancal/dark_current/tests/test_dark_sub.py
romancal/datamodels/core.py
romancal/datamodels/dynamicdq.py
romancal/datamodels/extension.py
romancal/datamodels/gls_rampfit.py
romancal/datamodels/image.py
romancal/datamodels/level1.py
romancal/datamodels/open_impl.py
romancal/datamodels/ramp.py
romancal/datamodels/rampfitoutput.py
romancal/flatfield/flat_field.py
romancal/flatfield/flat_field_step.py
romancal/lib/basic_utils.py
romancal/stpipe/core.py
romancal/tests/base_classes.py
setup.cfg

Closes #176
Resolves RCAL-131
This PR addresses the warnings and error list in the code checking. Updated most of the code modules to fix pep8 errors. I did not tackle the regression tests and they will be addressed separately. 
Checklist

Update setup.cfg to match JWST warnings & error list and initial pass for code fixes.

---

JenkinsfileRT

Closes # 203
Resolves RCAL-149
Updates CRDS_PATH from /data1 to CRDS_PATH=${WORKSPACE}/roman-crds-test-cache
as J Hunkeler suggests. 
Checklist

RCAL-149 Update CRDS_PATH for Jenkins

---

JenkinsfileRT

Closes #
Resolves RCAL-
Checklist

Rcal 149 update CRDS env variable and double " to single '

---

docs/roman/flatfield/index.rst
docs/roman/flatfield/main.rst

Closes #
Resolves RCAL-135
This PR addresses the description section for the flat fielding step.
Checklist
- [ x] Documentation

Add description section for flat fielding. (RCAL-135)

---

JenkinsfileRT
requirements-sdp.txt

Closes #
Resolves RCAL-157
Updates requirements asdf, lxml and urllib 3
Checklist
- [ x] Documentation

Rcal 157 Update requirements in prep for June 15 Build 0.2 release

---

JenkinsfileRT

Change the regtest  CRDS context for build 0.2.

Change the CRDS context

---

JenkinsfileRT
romancal/regtest/test_wfi_flat_field.py

This PR changes the model class used in the regression tests to the new tagged model and updates the JenkinsfileRT context to roman_0007.pmap.
Checklist

Update model class in regtest and set JenkinsfileRT context to roman_0007.pmap

---

requirements-sdp.txt

This PR updates the crds requirement in requirements-sdp.txt (oops, forgot about this one in #218)
Checklist

Update crds requirement in requirements-sdp.txt

---

requirements-sdp.txt
setup.cfg

This PR updates stpipe and stdatamodels requirements.
Checklist

Update stpipe and stdatamodels requirements

---

CHANGES.rst
README.md

Closes #226
Resolves RCAL-
This PR addresses changes for 0.3.1 to add CRDS grism test.
Checklist
- [ x] Documentation

Update Changes.rst and README.md for 0.3.1 release

---

CHANGES.rst
README.md

Closes #241
Resolves RCAL-172
Checklist

Rcal-172  Update README URL's and text

---

romancal/jump/jump_step.py

Closes #
Resolves RCAL-81
This is the step code for the jump detection step, which call the jump code in stcal
Checklist

Develop jump code for Roman (RCAL-81)

---

CHANGES.rst
setup.cfg

Closes #245
Resolves RCAL-225
This PR fixes the crashes in Jenkins due to updates in RAD & RDM libraries (that romancal isn't ready for).
Checklist
- [X ] Tests

Fixing RAD and RDM version dependencies.

---

docs/roman/references_general/readnoise_reffile.inc
docs/roman/references_general/readnoise_reffile.rst
docs/roman/references_general/readnoise_selection.inc
docs/roman/references_general/readnoise_selection.rst

Closes #
Resolves RCAL-141
Documentation for Roman read noise reference files
Checklist
- [X ] Documentation

Documentation of readnoise reference files (RCAL-141)

---

docs/conf.py

This PR attempts to resolve the doc build failure due to changes in sphinx_astropy 1.5.0.
Checklist

Replace pytest-astropy sphinx extension with pytest-doctestplus

---

CHANGES.rst
JenkinsfileRT
README.md
docs/conf.py

Closes #270
Resolves RCAL-179 
readthedocs reverted to trying to git clone from master instead of main. So I manually set "latest" to main in the advanced settings on readthedocs.
Updated some formatting in text files. 
Checklist
- [x ] Documentation
- [ x] Label(s)

Rcal 179 Updates for triggering readthedocs

---

CHANGES.rst
romancal/regtest/test_wfi_dq_init.py
romancal/regtest/test_wfi_flat_field.py

Closes #265 & #253 
Resolves RCAL-182
This PR adds regressoin tests for dq_init utilizing mask files in CRDS.
Checklist

RCAL 182 Added DQ_Init regression tests.

---

docs/roman/package_index.rst
docs/roman/ramp_fitting/arguments.rst
docs/roman/ramp_fitting/description.rst
docs/roman/ramp_fitting/index.rst
docs/roman/ramp_fitting/reference_files.rst

Closes #
Resolves RCAL-130
This PR addresses RCAL-130: documentation for Roman ramp fitting
Checklist
- [ X] Documentation

Roman ramp fitting docs (RCAL-130)

---

CHANGES.rst
romancal/regtest/test_jump_det.py

Closes # 
Resolves RCAL-220
This PR Add simple regression test for Jump detection.
Checklist
- [x ] Tests
- [ x] Documentation
- [ x] Change log
- [ x] Label(s)

RCAL-220 Added regresson test for Jump Detection

---

tox.ini

Attempt to fix testing with coverage.

fix for cov

---

CHANGES.rst
romancal/flatfield/flat_field.py
romancal/flatfield/flat_field_step.py
romancal/regtest/test_wfi_flat_field.py

Closes #349
Resolves RCAL-229
This PR is to update the output of the flat field step to append _flat to the filename. 
Checklist
- [ x] Tests
../../romancal/romancal/regtest/test_wfi_flat_field.py .s.                                                    [100%]
============================== 2 passed, 1 skipped, 4 deselected in 678.58s (0:11:18)
- [x ] Documentation
- [ x] Label(s)

RCAL-229 Updated flat_field_step to append flat to the filename

---

CHANGES.rst
romancal/lib/dqflags.py
romancal/regtest/test_wfi_saturation.py
romancal/saturation/__init__.py
romancal/saturation/saturation.py
romancal/saturation/saturation_step.py
romancal/saturation/tests/test_saturation.py
romancal/step.py
romancal/stpipe/integration.py

Closes #312 
Resolves RCAL-218
This PR addresses implementation of saturation correction using stcal, roman_datamodels and romancal.stpipe
Checklist
- [x ] Tests
- [x ] Documentation. (code comments, full docs in a separate PR) 

Rcal 218 saturation

---

CHANGES.rst
romancal/regtest/test_jump_det.py

Closes #
Resolves RCAL-230
Update the files after the updates to RAD and roman_datamodels
Checklist
- [ X] Tests
- [X ] Change log

Updated names of input and truth files

---

CHANGES.rst
romancal/linearity/__init__.py
romancal/linearity/linearity_step.py
romancal/step.py
romancal/stpipe/integration.py

Closes #
Resolves RCAL-217
This PR addresses RCAL-217; "Implement Linearity correction using STCAL, RDM & stpipe". This has only been tested using an override reference file. I will submit separate PRs for the documentation and tests later. 
Checklist
- [X ] Change log

First version of implementation of linearity correction for RCAL-217

---

CHANGES.rst
docs/roman/assign_wcs/index.rst
docs/roman/assign_wcs/main.rst
docs/roman/package_index.rst
romancal/assign_wcs/__init__.py
romancal/assign_wcs/assign_wcs_step.py
romancal/assign_wcs/pointing.py
romancal/assign_wcs/tests/test_wcs.py
romancal/assign_wcs/utils.py
romancal/step.py
romancal/stpipe/integration.py

Closes #353
Resolves RCAL-246
This PR adds an `assign_wcs` step to romancal.
Fixed formatting of `Changes.rst`.
Checklist

RCAL-246: Add assign_wcs step

---

romancal/ramp_fitting/ramp_fit_step.py
romancal/regtest/test_jump_det.py
romancal/regtest/test_wfi_flat_field.py

This PR updates the regression test input and output that is affected by the addition of the cal_logs attribute, and fixes a bug in ramp_fit_step that was uncovered by the tests.
The new files are staged here: /eng/ssb/eslavich/roman-artifacts, @ddavis-stsci can you upload those to artifactory for me?  I don't have write permissions for the roman-pipeline area.
Checklist

Update regtests for new required cal_logs attribute

---

docs/roman/linearity/arguments.rst
docs/roman/linearity/description.rst
docs/roman/linearity/index.rst
docs/roman/linearity/reference_files.rst
docs/roman/package_index.rst
docs/roman/references_general/linearity_reffile.inc
docs/roman/references_general/linearity_reffile.rst
docs/roman/references_general/linearity_selection.inc
docs/roman/references_general/linearity_selection.rst

Closes #
Resolves RCAL-240
This PR addresses RCAL-240: "Documentation for Linearity correction in RTD". The code for this step was covered by RCAL-217 (PR #360, which has been merged)
Checklist
- [X ] Documentation

Add linearity correction documentation (RCAL-240)

---

CHANGES.rst
romancal/regtest/test_wfi_pipeline.py

Closes #
Resolves RCAL-242
This PR addresses tests to cover SOC-604. The tests cover:
In Wide Field Imaging mode, the DMS shall generate Level 2 science data products consisting of exposures corrected for instrument artifacts, including the following information for each calibrated exposure:
(a) Effective depth for each pixel
(b) Effective exposure time for each pixel
(c) World Coordinate System information.
Checklist
- [x ] Tests

Initial attempt at Image regtests.

---

requirements-sdp.txt

Closes #
Resolves RCAL-
This PR updates the CRDS version to 11.5.2 
Checklist

Update CRDS version to 11.5.2

---

.github/workflows/roman_ci.yml
tox.ini

Closes #347
Resolves RCAL-245
This PR addresses adds Python 3.10 to the test matrix
Checklist

RCAL-245: Test with Python 3.10

---

CHANGES.rst
romancal/flatfield/tests/test_flatfield.py
romancal/saturation/tests/test_saturation.py
romancal/stpipe/tests/test_core.py
setup.cfg

Resolves RCAL-290
This PR addresses updated tests to utilize new maker function code.
Checklist

RCAL-290: Update Tests to New Versions of RDM Utility Functions

---

.github/pull_request_template.md
.readthedocs.yml
JenkinsfileRT
README.md
setup.cfg

This PR addresses makes updates to the test and project documentation files
- Added a link for the jira ticket
- Changed the python version in the Jenkins file to 3.9
- Updated Python requirement in README and setup files
- Updated other dependency requirements
Checklist

Various build changes

---

.gitignore
CHANGES.rst
docs/roman/introduction.rst

Resolves RCAL-39
This PR lists the possible suffixes for pipeline processing in read the docs.
Checklist

RCAL-39 List of the possible pipeline products added to RTD

---

CHANGES.rst
docs/roman/datamodels/datamodels_asdf.rst
docs/roman/datamodels/index.rst

GitHub issue, Closes #341
Resolves [RCAL-307(https://jira.stsci.edu/browse/RCAL-307)
This PR adds documentation for the info and search methods to the roman datamodels documentation. 
Checklist

Rcal-307 Adds examples of using the info and search methods for roman datamodels

---

romancal/jump/tests/test_jump_step.py

fix instrument name in test

---

JenkinsfileRT

Set context for regression tests

---

setup.cfg

This PR updates the versions of dependencies in preparation for release.
Checklist

Update versions of dependencies

---

CHANGES.rst
docs/roman/pipeline/exposure_pipeline.rst
docs/roman/ramp_fitting/description.rst

GitHub issue, Closes #441 
Resolves [RCAL-289](https://jira.stsci.edu/browse/RCAL-289)
This PR updates the documentation for DMS build 0.5
Checklist

RCAL-289 Updates for DMS release 0.5

---

romancal/dq_init/tests/test_dq_init.py

Small fix for dq_init test to add mask model

add mask model

---

requirements-dev.txt

GitHub issue, Closes #464
This PR updates romanad (pipy) to the local rad development repository. 
Checklist

GH464 Update reqirements-dev.txt

---

requirements-dev.txt

GitHub issue, Closes #464 
This PR removes rad.git requirements-dev.txt so that roman_datamodels controls the installed version of rad
Checklist

464 update requirements dev for rad

---

JenkinsfileRT
JenkinsfileRT_dev

This PR updates the CRDS context to roman_0031.pmap
Checklist

Update CRDS context to roman_0031.pmap

---

JenkinsfileRT
JenkinsfileRT_dev
requirements-sdp.txt

This PR updates the CRDS context to roman_0032.pmap for testing.
Checklist
- [N/A] Documentation
- [N/A] Change log

Update crds context to 0032

---

scripts/okify_regtests

This PR updates the JWST okify script to work with Roman artifactory data. 
Checklist
- [N/A] Tests
- [N/A] Documentation
- [N/A] Change log

Update okify script to work with Roman artifactory data

---

CHANGES.rst
romancal/jump/jump_step.py
setup.cfg

Adds in 'max_cores' parameter for multiprocessing.

JP-2581: enable multiprocessing for jump

---

romancal/linearity/linearity_step.py

Account for possible zero frame in linearity

---

requirements-sdp.txt

This PR unpins stcal and pyparsing for testing in preparation for romancal 0.7.1
Checklist

Updates for stcal

---

romancal/dark_current/tests/test_dark.py

Cleans up file ('dark_out.asdf') generated when running the unit tests.
Checklist

Clean up file generated when running tests

---

CHANGES.rst
romancal/dark_current/tests/test_dark.py
romancal/dq_init/tests/test_dq_init.py
romancal/jump/tests/test_jump_step.py
setup.cfg

GitHub issue, Closes #519 
Resolves [RCAL-349](https://jira.stsci.edu/browse/RCAL-349)
This PR updated tests to account for the change in dimensionality of the err variable in ramp datamodel.
Checklist

RCAL-349: Update RomanCal For Error Dimensionality Fix

---

CHANGES.rst
romancal/ramp_fitting/ramp_fit_step.py
romancal/ramp_fitting/tests/test_ramp_fit.py

GitHub issue, Closes #434 
Resolves [RCAL-309](https://jira.stsci.edu/browse/RCAL-309)
This PR added multiprocessing ramp test. Fixed ols ramp fit. Updated ramp_fit to add photometry to image file generation.
Checklist

RCAL-309: Ramp Fit Multiprocessing IndexError

---

.github/pull_request_template.md

update pull request template to be more explicit

---

CHANGES.rst
romancal/flatfield/flat_field.py
romancal/flatfield/flat_field_step.py

GitHub issue, Closes #505 
Resolves [RCAL-341](https://jira.stsci.edu/browse/RCAL-341)
This PR removed try/except condition on Flat Reference file CRDS lookup.
Checklist

RCAL-341: Update Flat field code and tests to use N/A from CRDS

---

CHANGES.rst
docs/roman/references_general/distortion_reffile.rst
docs/roman/references_general/distortion_selection.inc

Resolves [RCAL-320](https://jira.stsci.edu/browse/RCAL-320)
Closes #463 
This PR updates the docs to include information about the distortion reference file used in the `assign_wcs` step.
Since most of the info was already present in the docs, this PR should be a minor update.

Docs update on the distortion file.

---

romancal/assign_wcs/assign_wcs_step.py

This PR addresses all the comments made by @nden on [PR #539](https://github.com/spacetelescope/romancal/pull/539).
- `add_s_region` is not public anymore;
- `add_s_region`'s docstring was reformatted to comply with `numpy`'s conventions.

Make add_s_region private and reformat docstring.

---

.github/workflows/roman_ci.yml

follow-on to #511
This PR freezes the versions of actions used in the GitHub Actions workflow, to ensure that API changes don't break the unit tests
**Checklist**

freeze action versions

---

CHANGES.rst
setup.cfg

Addresses [JP-2675](https://jira.stsci.edu/browse/JP-2675)
This PR updates the `stpipe` dependency requirement to utilize the newest patch (https://github.com/spacetelescope/stpipe/pull/62).
**Checklist**

update `stpipe` requirement to `>=0.4.1`

---

requirements-dev.txt

Closes #
This PR unpins the version of stpipe and reverts to the development version for
the devdeps testing. 
**Checklist**
- [] added entry in `CHANGES.rst` under the corresponding subsection
- [] updated relevant tests
- [] updated relevant documentation

Unpin stpipe version in development requirements

---

JenkinsfileRT
JenkinsfileRT_dev

Closes #
This PR updates the CRDS pmap to context 0038 to address the filter updates (W146 -> F146)
**Checklist**
- [x ] updated relevant milestone(s)
- [x ] added relevant label(s)

Update CRDS Context

---

README.md

Minor fixes to README badges
**Checklist**

fix README badge, remove redundant section

---

setup.cfg

This PR utilizes the newest version of `roman_datamodels`.
**Checklist**

pin `roman_datamodels` to newest feature release

---

docs/roman/flatfield/main.rst

Resolves [RCAL-351](https://jira.stsci.edu/browse/rcal-351)
Closes #525 
This PR updates the documentation for the error propagation in the flat field step. 
**Checklist**
- [N/A ] added entry in `CHANGES.rst` under the corresponding subsection
- [N/A ] updated relevant tests

RCAL-351 Update flat field documentation

---

docs/conf.py

Update to `conf.py` to reference directories in `docs`
**Checklist**

set docs directories in `conf.py`

---

docs/roman/introduction.rst
docs/roman/package_index.rst
docs/roman/stpipe/call_via_call.rst
docs/roman/stpipe/call_via_run.rst
docs/roman/stpipe/config_asdf.rst
docs/roman/stpipe/devel_logging.rst
docs/roman/stpipe/devel_pipeline.rst
docs/roman/stpipe/devel_step.rst
docs/roman/stpipe/index.rst
docs/roman/stpipe/parameter_files.rst
docs/roman/stpipe/user_logging.rst
docs/roman/stpipe/user_pipeline.rst
docs/roman/stpipe/user_step.rst

Resolves [RCAL-396](https://jira.stsci.edu/browse/JP-396)
Closes #
This PR adds documentation for running and configuring the pipeline from python as well as from the command line. 
**Checklist**

Rcal-396 Document running the rcal pipeline from python

---

.github/workflows/roman_ci.yml

This PR adds Python 3.11 to the testing workflow.
**Checklist**

add Python 3.11 to CI tests

---

tox.ini

related to https://github.com/spacetelescope/jwst/issues/7383
**Checklist**

changes for `tox>=4.0` release

---

CHANGES.rst
JenkinsfileRT
JenkinsfileRT_dev
requirements-sdp.txt
romancal/pipeline/exposure_pipeline.py

Resolves [RCAL-431](https://jira.stsci.edu/browse/JP-nnnn)
Closes #
This PR updates the suffix for the stored filename for spectroscopic data to include the suffix _cal and updates the CRDS context to 0039. 
**Checklist**

RCAL-431 Update suffix and CRDS context

---

.github/labeler.yml
.github/workflows/roman_ci.yml
JenkinsfileRT
tox.ini

This PR adds tracers for Datadog
**Checklist**

add Datadog CI agent

---

JenkinsfileRT
JenkinsfileRT_dev

This PR attempts to fix the issue in Jenkins jobs 
```
ModuleNotFoundError: No module named 'tqdm'
```
**Checklist**

update `conda` in Jenkins environment

---

CHANGES.rst
pyproject.toml
romancal/dark_current/dark_current_step.py
romancal/dark_current/tests/test_dark.py
romancal/dq_init/tests/test_dq_init.py
romancal/flatfield/tests/test_flatfield.py
romancal/jump/jump_step.py
romancal/jump/tests/test_jump_step.py
romancal/ramp_fitting/ramp_fit_step.py
romancal/ramp_fitting/tests/test_ramp_fit.py
romancal/saturation/saturation.py
romancal/saturation/tests/test_saturation.py

Resolves [RCAL-440](https://jira.stsci.edu/browse/RCAL-440])
Closes #
This PR implements support for quantities in reference files. Updated unit tests for these changes.
NOTE: pyproject.toml is temporarily pointing to dev branches to help tests pass.
**Checklist**

RCAL-440 Add support for Reference File Quantities

---

romancal/tweakreg/tweakreg_step.py

This PR addresses an unnecessary appendage of the source catalog to the datamodel schema and also provides small code clean-ups.
**Checklist**

Clean up and small refactoring.

---

pyproject.toml

This PR addresses issues with testing that arise from upper pins on dependencies.
**Checklist**

remove upper pins from dependencies

---

CHANGES.rst
romancal/source_detection/source_detection_step.py

Resolves [RCAL-537](https://jira.stsci.edu/browse/RCAL-537)
Closes #
This PR fixes source detection institution (which is causing regression test errors).
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/113/
**Checklist**

Fix source detection object instantiation.

---

JenkinsfileRT
JenkinsfileRT_dev

Closes #
This PR updates the CRDS context in the Jenkins files to the version needed for the new data files
and reference files, roman_0047.pmap
**Checklist**

Update CRDS context for 23Q3_B10

---

romancal/tweakreg/tests/test_tweakreg.py
romancal/tweakreg/tweakreg_step.py

This PR adds more unit tests to improve code coverage for TweakReg.
**Regression tests are not passing, but none of the failures are related to TweakReg**:
- https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/258/#showFailuresLink
**Checklist**

Increase code coverage for TweakReg.

---

README.md

Resolves [RCAL-613](https://jira.stsci.edu/browse/RCAL-613)
This PR updates the build instructions in the README
**Checklist**
- [N/A] ~added entry in `CHANGES.rst` under the corresponding subsection~
- [N/A] ~updated relevant tests~
- [N/A] ~updated relevant milestone(s)~

update build instructions in README

---

README.md

Resolves [RCAL-617](https://jira.stsci.edu/browse/rcal-617)
Closes # (It appears the bot may be down again). 
This PR updates the README.md file for B10 & B11
**Checklist**

RCAL-617 Update readme for release 11 (23Q3_B10) & placeholders for 12 (23Q4_B11)

---

README.md
docs/roman/pipeline_installation.rst

Use CRDS public server

---

requirements-dev.txt
tox.ini

Update `requirements-dev.txt` so that it contains all the information it needs instead of some of it being split into `tox.ini`.
**Checklist**

Cleanup the requirements-dev

---

.github/pull_request_template.md

This PR adds a reminder to run regression tests as a checkbox to PRs
**Checklist**

add checkbox for regression tests to the pull request template

---

pyproject.toml

Resolves [RCAL-646](https://jira.stsci.edu/browse/rcal-646)
Closes #882 
This PR adds asn_from_list to scripts section in pyproject.toml so that it is installed in the 
bin directory with the other scripts. 
pip install -e .[test,docs]
...
>which asn_from_list
>...envs/rcal_dev/bin/asn_from_list
**Checklist**
The regression tests show no unexpected failures, all are related to needed input file updates
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/378/

RCAL-646 Update to install asn_from_list

---

CHANGES.rst
pyproject.toml
scripts/asn_from_list

This PR fixes the `asn_from_list`
**Checklist**

fixed `asn_from_list` script

---

docs/index.rst
docs/roman/pipeline/exposure_pipeline.rst
docs/roman/pipeline/highlevel_pipeline.rst
docs/roman/pipeline/index.rst
docs/roman/pipeline/main.rst
docs/roman/pipeline_installation.rst
docs/roman/pipeline_levels.rst
docs/roman/pipeline_parameters.rst
docs/roman/pipeline_run.rst

Resolves [RCAL-727](https://jira.stsci.edu/browse/RCAL-727)
Closes #1034 
This PR updates the documentation for the 24Q1_B12 release. 
Section for HLP added
Update ELP for combined Jump/Ramp fitting
Added source detection and tweakreg to the steps and tables
**Checklist**
- [N/A] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

Rcal 727 Add High Level Pipeline documentation, various updates

---

CHANGES.rst
docs/roman/outlier_detection/arguments.rst
romancal/conftest.py
romancal/outlier_detection/outlier_detection.py
romancal/outlier_detection/outlier_detection_step.py
romancal/outlier_detection/tests/test_outlier_detection.py
romancal/resample/resample.py

Resolves [RCAL-502](https://jira.stsci.edu/browse/RCAL-502)
This PR adds unit tests to the newly added outlier detection pipeline module.
The regression test for the outlier detection step will be added soon.
**Regression tests results**
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/516/
**Checklist**

Add unit tests and outlier module refactoring.

---

pyproject.toml

tweakwcs 0.8.6 includes an update to the image alignment step that dramatically reduces memory usage and improves speed for aligning 18 detector Roman arrays to Gaia.  This updates the dependency of romancal to require that version.
Passing regression tests: https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/587/

Update tweakwcs dependency

---

docs/roman/assign_wcs/main.rst

Clarify how to get V2/V3_REF

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml
.github/workflows/tests_devdeps.yml
README.md
docs/roman/pipeline_installation.rst
pyproject.toml

resolves [SCSB-145](https://jira.stsci.edu/browse/SCSB-145)
propagate Astropy's deprecation of Python 3.9 to downstream packages
> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:

[SCSB-145] require Python 3.10

---

CHANGES.rst
romancal/pipeline/highlevel_pipeline.py
romancal/regtest/test_hlp_pipeline.py
romancal/resample/resample.py

Resolves [RCAL-783](https://jira.stsci.edu/browse/RCAL-783)
Closes #1129 
Closes #1130
This PR allows the high level pipeline to use updates in Outlier_detection and tweakreg and adds an initial 
regression test for the hlp. 
**Checklist**
- [N/A] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)
The regression tests are up and running again and the passing test for this PR is at 
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/689/
The regular regression tests are currently not working. The step is running as 
```
strun --debug roman_hlp L3_regtest_asn.json
2024-03-13 12:16:21,768 …
```

Rcal-783 Update the high level pipeline for B14

---

CHANGES.rst
romancal/stpipe/core.py
romancal/stpipe/tests/test_core.py

Part of  [RCAL-823](https://jira.stsci.edu/browse/RCAL-823)
Closes #
**Checklist**
Passing regression tests
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/720/

Fix finalize

---

CHANGES.rst
romancal/assign_wcs/utils.py
romancal/lib/tests/helpers.py
romancal/resample/resample.py
romancal/resample/tests/test_resample.py

Resolves [RCAL-700](https://jira.stsci.edu/browse/RCAL-799)
This PR fills in the Level 3 wcsinfo meta
**Checklist**

RCAL-799: Populate the Level 3 wcsinfo

---

romancal/outlier_detection/tests/test_outlier_detection.py

Resolves [RCAL-802](https://jira.stsci.edu/browse/RCAL-802)
This PR adds a unit test to ensure `OutlierDetectionStep` always return a `ModelContainer` with the updated datamodels. No changes to the step code were necessary.
**Regression Tests**
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/724/
**Checklist**

RCAL-802: Update outlier detection step to return a ModelContainer if input is an association file.

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/data.yml

Resolves [SCSB-139](https://jira.stsci.edu/browse/SCSB-139)
**Checklist**

update actions version

---

JenkinsfileRT_dev

Closes #
This PR updates python 3.9 to 3.11 in JenkinsfileRT_dev
**Checklist**
- [N/A ] added entry in `CHANGES.rst` under the corresponding subsection
Fixes the photutils build issue but reveals other issues that will need tickets for fixes. 
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-devdeps/537/

Update python from 3.9 to 310 in JenkinsfileRT_dev

---

romancal/associations/lib/rules_level2.py
romancal/pipeline/exposure_pipeline.py
romancal/skymatch/region.py

apply minor fixes for sonarqube

---

romancal/source_catalog/tests/test_source_catalog.py

This should fix the issue mentioned by George Cleary on Slack: https://stsci.slack.com/archives/C01FP900P38/p1718113704757169
**Checklist**

Fix comparison operator.

---

romancal/patch_match/test/test_patch_match.py

This fixes an issue encountered during testing for https://github.com/spacetelescope/romancal/pull/1222 which revealed that the patch match tests modify global state (impacting later tests). A relatively minimal reproducer (using the #1222 branch) is to run:
```
pytest --bigdata romancal/patch_match/test/test_patch_match.py romancal/regtest/test_mos_pipeline.py::test_hlp_mosaic_pipeline
```
which triggers the `IndexError: index 0 is out of bounds for axis 0 with size 0` error when the mosaic pipeline fails to find the patch table entry for the requested patch. This is due to patch table modification here:
https://github.com/spacetelescope/romancal/blob/747667895099a80ef283838a8499bac391cb1c46/romancal/patch_match/test/test_patch_match.py#L43
(which is why running just the …

use monkeypatch in patch_match tests to avoid global state change

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml
.github/workflows/tests_devdeps.yml

Resolves [SCSB-169](https://jira.stsci.edu/browse/SCSB-169)
[<img width="333" alt="image" src="https://github.com/user-attachments/assets/51c0f9ab-a75b-4df0-8fcb-f611c00e92db">](https://github.com/zacharyburnett/romancal/actions/workflows/roman_ci.yml)
**Checklist**

[SCSB-169] add user input to specify `CRDS_CONTEXT`

---

changes/1485.multiband_catalog.rst
pyproject.toml
romancal/lib/suffix.py
romancal/multiband_catalog/__init__.py
romancal/multiband_catalog/background.py
romancal/multiband_catalog/detection_image.py
romancal/multiband_catalog/multiband_catalog_step.py
romancal/multiband_catalog/tests/test_multiband_catalog.py
romancal/multiband_catalog/utils.py
romancal/regtest/test_catalog.py
romancal/regtest/test_multiband_catalog.py
romancal/scripts/make_regtestdata.sh
romancal/source_catalog/source_catalog.py
romancal/source_catalog/source_catalog_step.py
romancal/step.py
romancal/stpipe/integration.py
romancal/tests/dms_requirement_tests.json

Resolves [RCAL-943](https://jira.stsci.edu/browse/RCAL-943)
Closes #1486 
This PR adds a  new pipline step, `MultibandCatalogStep`, for creating multiband catalogs from a detection image, representing the combination of all bands.  It also adds Kron photometry to `SourceCatalogStep` (incl. the multiband catalog).
I think this work falls under [RCAL-873](https://jira.stsci.edu/browse/RCAL-873).
CC: @schlafly 
- …

RCAL-943: Add a step for creating multiband source catalogs

---

.github/workflows/tests_devdeps.yml

This PR removes the python 3.10 devdeps jobs.
- …

remove python 3.10 devdeps jobs

---

romancal/resample/tests/test_resample.py

Fixes a bug introduced in #1567
- …

Fix a bad rebase

---

1542.mosaic_pipeline.rst
changes/1593.exposure_pipeline.rst
changes/1593.resample.rst
changes/1593.saturation.rst
docs/roman/package_index.rst
docs/roman/pipeline/exposure_pipeline.rst
docs/roman/references_general/references_general.rst
docs/roman/resample/arguments.rst
docs/roman/stpipe/config_asdf.rst
docs/roman/stpipe/user_pipeline.rst
romancal/pipeline/exposure_pipeline.py
romancal/resample/resample.py
romancal/resample/resample_step.py
romancal/resample/tests/test_resample.py

Closes #1388
Closes #1397
Closes #1524
Closes #1559
Closes #1576
This PR closes a number of minor issues.
- remove the top level changelog fragment https://github.com/spacetelescope/romancal/issues/1576
- fix broken reference file table https://github.com/spacetelescope/romancal/issues/1559
- fix elp documention description of arguments and fully saturated input handling https://github.com/spacetelescope/romancal/issues/1524
- add saturation step to package index https://github.com/spacetelescope/romancal/issues/1397
- remove unused items from resample step specification https://github.com/spacetelescope/romancal/issues/1388
Regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/12997183146
- …

Fix minor issues with documentation and unused arguments, etc

---

README.md

remove reference to `plwishmaster`

---

.github/workflows/download_data.yml

WIP rcal-1021
This is an intermediate PR to prime the new STPSF cache in the CI

download stpsf cache along with webbpsf

---

docs/index.rst

Precipitated by [SCSB-194](https://jira.stsci.edu/browse/SCSB-194)
analogous to https://github.com/spacetelescope/jwst/pull/8642
adds version information to the homepage of the docs, in preparation of removing the `stable` branch and letting RTD build its own `stable` version from the latest release
- …

[DOCS] add version to central page

---

changes/1661.flux.rst
romancal/flux/flux_step.py

Closes #1662
This PR changes the flux step calculation to use in-place operations instead of allocating new arrays. This reduces the memory usage of the flux step (and mosaic pipeline). See #1660 for context.
Regression tests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/13972364505
- …

compute flux inplace

---

docs/roman/datamodels/metadata.rst

Skip a doctest that will fail when https://github.com/spacetelescope/rad/pull/560 is merged (the schema uri changes).
I ran this locally with the above PR (and corresponding roman_datamodels PR) and the test is successfully skipped with this PR (and fails on maiin).
We can unskip this after the PR is merged.
Regtests were not run as the unit tests should cover this one line change.
- …

skip a doctest while schemas are updated

---

romancal/source_catalog/source_catalog.py

Resolves [RCAL-1048](https://jira.stsci.edu/browse/RCAL-1048)
Closes #1695.
This PR implements the `is_extended` algorithm.  This will eventually need to be updated to calculate the `ee_ratio` from a reference file (not yet avaliable).
- …

Implement placeholder is_extended

---

romancal/assign_wcs/utils.py
romancal/resample/resample_step.py
romancal/resample/resample_utils.py

Resolves [RCAL-1054](https://jira.stsci.edu/browse/RCAL-1054)
This PR corrects the definition of pixel scale ratio as used in resampling of imaging data (NOTE: for JWST, spectral resampling may use opposite definition to the one used in imaging)
- …

Update docs to reflect correct definition for pixel scale ratio

---

pyproject.toml

Resolves [RCAL-1058](https://jira.stsci.edu/browse/RCAL-1058)
Closes #1721
This PR fixed the build warnings by:
* Adding several missing `__init__.py` files in `tests` directories
* Updating `pyproject.toml` to only explicitly include files listed in package-data
- …

Fix build warnings about package configuration

---

changes/1749.general.rst
pyproject.toml

Closes #1748
This PR bumps the minimum asdf version to 4.1.0 because that is also the requirement for `rad`.
- …

Require asdf 4.1.0+

---

tox.ini

Remove unused numpy environments in tox config

---

changes/1797.assign_wcs.rst
romancal/assign_wcs/assign_wcs_step.py
romancal/assign_wcs/tests/test_wcs.py
romancal/assign_wcs/utils.py
romancal/skycell/match.py

use `stcal.alignment.util.wcs_bbox_from_shape`

---

romancal/orientation/set_telescope_pointing.py

This PR addresses a bug found while examining an issue found in RSDP. The issue, still yet unresolved, is that when the MRT6 data is processed with actual pointing information, the VO query for catalog objects takes too long and times out. During research, it was found the wcsinfo.roll_ref value was being incorrectly calculated.
- …

fix roll calculation

---

pyproject.toml

https://github.com/spacetelescope/romancal/pull/1691 modified the stcal pin pointing it to a branch. This caused some devdeps failures last night as the branch isn't spacetelescope:main.
This PR sets the stcal dependency back to spacetelescope:main.
- …

set stcal dep to main
