spacetelescope/romancal

romancal/datamodels/extension.py
romancal/datamodels/tests/test_extension.py
setup.cfg

This PR adds an extension that registers Roman datamodels schema URIs with asdf.  The test doesn't currently pass, but will when @PaulHuwe's update to the referencefile.schema.yaml `id` field is merged.

Create asdf extension for datamodels schemas

---

romancal/datamodels/__init__.py
romancal/datamodels/core.py
romancal/datamodels/open_impl.py
romancal/datamodels/tests/test_extension.py
romancal/datamodels/tests/test_models.py
romancal/datamodels/tests/test_open.py
setup.cfg

This PR adds the `RomanDataModel` base class and `romancal.datamodels.open`.  The logic in `open` that selects the model class is just stubbed out for now, since we haven't settled on how that's going to work (and anyway, we haven't implemented any real models yet).

Create RomanDataModel and open function

---

.readthedocs.yml

For RCAL-18  ("Enable pipeline documentation build on readthedocs"), the file .readthedocs.yml is recommended to configure the documentation builds.

yml file needed for RCAL-18

---

romancal/datamodels/__init__.py
romancal/datamodels/core.py
romancal/datamodels/open_impl.py
romancal/datamodels/referencefile.py
romancal/datamodels/schemas/core.schema.yaml
romancal/datamodels/schemas/reference_files/flat.schema.yaml
romancal/datamodels/schemas/reference_files/referencefile.schema.yaml
romancal/datamodels/tests/test_models.py
romancal/datamodels/tests/test_open.py

Added tests for core, referencefile, and flat schemas. Updated the schemas for required keywords and modified time types. Some tests are commented out due to known asdf errors. (RCAL-25, RCAL-26, RCAL-50, RCAL-52)

Initial Reference File Testing

---

romancal/flatfield/README.md

Building documentation for romancal using readthedocs requires the existence of the directory romancal/flatfield, which will eventually contain code for the flatfield step.  Github only understands files, not directories (empty or not), so I've added this dummy file to the flatfield directory; this file will be removed once python files have been added to the directory.

Adding dummy README file to placate readthedocs build.

---

docs/roman/includes/standard_keywords.inc
docs/roman/references_general/flat_selection.inc

Adding more files required for the readthedocs build, as shown from the build log. There is 1 more error (which I am still investigating) from that log, regarding a missing class in the datamodels module.

Additional files required by readthedocs

---

docs/roman/datamodels/attributes.rst

This change corrects an error in a path in the docs that appeared in the readthedocs build log.

Corrected path.

---

docs/index.rst

Including these files in the index file addresses the problem of having an empty document page being built.

Included rst files in index.rst

---

docs/index.rst
docs/roman/package_index.rst

Two of the index rst files in the romancal readthedocs needed updating. As more calibration steps are added, the corresponding rst files will be added.  The current roman/introduction.rst is a straight copy of the JWST version, so needs to be 'romanticized'.

Fixed 2 index rst files

---

docs/roman/datamodels/models.rst
docs/roman/datamodels/new_model.rst
docs/roman/datamodels/structure.rst
docs/roman/error_propagation/main.rst
docs/roman/introduction.rst

Replaced references to JWST with references to Roman in the readthedocs Roman Cal documentation.  Some areas will need embellishment or clarification as code development progresses.

Replaced JWST references with Roman

---

docs/roman/references_general/flat_reffile.inc

For the flat-fielding reference file documentation, remove some JWST references, per RCAL-49.

Removed more JWST references

---

romancal/ramp_fitting/ramp_fit_step.py

First commit for porting ramp fitting to Roman; for RVAL-72. This first version of the module ramp_fitting_step.py handles only single-integration datasets as will be the case for Roman. This version has been modified to recast the components of the input Roman Ramp Data Model  to a JWST Ramp Data Model, which is passed to the lower level functions in ramp_fit.py and utils.py; the results are recast back into a Roman Data Model.  It seems that the JWST versions of ramp_fit.py and utils.py can be used for Roman, but tests (once stpipe is in place) may prove otherwise.

First version of driver for ramp fitting step.

---

README.md

One of the tests I added recently requires access to a CRDS cache, but I forgot to add instructions on setting that up.

Add developer CRDS setup instructions to readme

---

romancal/datamodels/core.py
romancal/datamodels/open_impl.py
romancal/datamodels/schemas/core.schema.yaml
romancal/datamodels/tests/test_models.py
setup.cfg

Now that https://github.com/spacetelescope/stdatamodels/pull/44 has been merged, we can support `astropy.time.Time` objects in the meta.date attribute here.

Add automatic meta.date management to RomanDataModel

---

CHANGES.rst
romancal/stpipe/core.py

This PR sets the default extension for Roman products to `.asdf`. 
~It depends on spacetelescope/stpipe#17~

RCAL-95: set default output_ext to .asdf

---

README.md

Seems like the test server, now that it's available, will be more stable than dev.

Update readme to advise using roman-crds-test.stsci.edu

---

romancal/datamodels/schemas/core.schema.yaml

To satisfy RCAL-132. Adding cal_step to the core schema. cal_step is needed for all steps in the pipeline.

Add cal_step to schema, needed for all steps

---

romancal/dark_current/dark_sub.py
romancal/dark_current/tests/test_dark_sub.py

This PR adds unit tests for the dark current subtraction step.  In dark_sub.py are updates which includes a workaround for a bug in the update function in the datamodel library,  and an added warning suppression for the case of an empty slice.

Adding tests for dark current step.

---

CHANGES.rst
romancal/datamodels/tests/test_models.py

Resolves RCAL-136: Investigate Jenkins failure
- Added sorting to test parameters to preserve order for tests done by parallel pytest workers.
Checklist
- [unneeded] Documentation

RCAL-136 Jenkins Build31 Hot Fix

---

CHANGES.rst
romancal/datamodels/schemas/reference_files/wfi_img_photom.schema.yaml

Closes #
Resolves RCAL-109
This PR addresses RCAL-109. wfi_img_photom.schema.yaml is the WFI image Roman analog of the JWST file nrcimg_photom.schema.yaml.  As I understand , there is no wfss mode for Roman, so there is no equivalent of the JWST file nrcwfss_photom.schema.yaml.
Checklist

Photom schema file (RCAL-109)

---

romancal/conftest.py
romancal/lib/tests/helpers.py
romancal/regtest/conftest.py
romancal/regtest/regtestdata.py
romancal/regtest/test_wfi_flat_field.py
setup.cfg

Closes #18
Resolves RCAL-38
This PR ports the jwst RT infrastructure to romancal and adds one regression test.
The test will fail because the dates in the truth file and the output are different.
An option will be added to asdf diff to allow exclusion of a list of attributes.
In the future much of this infrastructure should be moved to a common place, most likely ci_watson.
Checklist

RCAL-38: Regression tests infrastructure

---

setup.cfg

This PR updates the package's asdf requirement, which no longer needs to specify master now that asdf 2.8.0 is released.
Checklist

Update asdf requirement to >= 2.8.0

---

CHANGES.rst
romancal/regtest/test_wfi_flat_field.py

Closes #
Resolves RCAL-164
This PR adds a grism model to the flat field regression tests.
Checklist
pytest --bigdata ~/src/Roman/romancal/romancal/regtest -k test_flat
===================================================== test session starts =====================================================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/ddavis/src/Roman/romancal, configfile: setup.cfg
plugins: asdf-2.8.0, arraydiff-0.3, remotedata-0.3.2, cov-2.11.1, ci-watson-0.5, xdist-2.2.1, hypothesis-6.3.1, filter-subpackage-0.1.1, openfiles-0.5.0, forked-1.3.0, astropy-header-0.1.2, doctestplus-0.9.0
collected 2 items …

Rcal-164 Add grism model to flat field regression tests

---

romancal/stpipe/tests/test_core.py

Closes #
Resolves RCAL-167
Adds a test for 628.3 - CRDS shall provide calibration reference files to the Exposure Level Processing for Wide Field Spectroscopy Mode (WSM).
- x[ ] Label(s)

add a test for retrieving a spectral file from CRDS

---

CHANGES.rst
romancal/jump/__init__.py
romancal/jump/jump_step.py
romancal/step.py
romancal/stpipe/integration.py

Closes #
Resolves RCAL-178
This PR adds the jump step for roman data. 
Checklist
- [ x] Tests
x
- [ x] Label(s)
strun --debug romancal.step.JumpStep l1_0006_science_raw_dqinitstep.asdf
2021-09-17 13:35:30,208 - CRDS - ERROR -  Error determining best reference for 'pars-jumpstep'  =   Unknown reference type 'pars-jumpstep'
2021-09-17 13:35:30,210 - stpipe.JumpStep - INFO - JumpStep instance created.
2021-09-17 13:35:30,237 - stpipe.JumpStep - INFO - Step JumpStep running with args ('l1_0006_science_raw_dqinitstep.asdf',).
2021-09-17 13:35:30,238 - stpipe.JumpStep - INFO - Step JumpStep parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.asdf', 'output_use_model': False, 'output_use_index': True, 'save_results': True, …

Rcal 178 Jump Step for Roman data

---

CHANGES.rst
romancal/ramp_fitting/__init__.py
romancal/ramp_fitting/ramp_fit_step.py
romancal/regtest/test_ramp_fitting.py
romancal/step.py
romancal/stpipe/integration.py
setup.cfg

Closes #279 
Closes #277 
Resolves RCAL-191
Resolves RCAL-189
This PR implements ramp_fitting using `stcal`, `roman_datamodels` and `romancal.stpipe`.
It needs spacetelescope/stcal#43, spacetelescope/rad#66 and  spacetelescope/rad#86 .
Fixed the formatting of `CHANGES.rst`.
Checklist

ramp_fitting using stcal and roman_datamodels

---

CHANGES.rst
romancal/jump/jump_step.py

Closes #319
Resolves RCAL-224
This PR updates pixel and dq arrays with the results from Jump detection. 
Note: the solution uses a copy to avoid a known error in the python 3.9 memory management. 
The error is 
UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
Once this is fixed 
pdq = pdq[0, :, :]
result.pixeldq = pdq.copy()
should become
result.pixeldq = pdq[0, :, :]
Checklist
- [ x] Tests
- [x ] Documentation
- [ x] Change log
pytest --debug --bigdata ~/src/Roman/romancal/romancal/regtest/ --basetemp=/Users/ddavis/src/Roman/develop/test/tmp_t/ -k test_jump_det
writing pytestdebug information to /Users/ddavis/src/Roman/develop/Jump/pytestdebug.log
.... …

RCAL-224 Update pixel and group dq arrays in results from Jump Detection

---

CHANGES.rst
romancal/jump/tests/test_jump_step.py

Closes #332 
Resolves RCAL-234
This PR updates temp readnoise file in jump tests to include required exposure keywords.
Checklist
- [x ] Tests

RCAL-234 Fix Jump Unit Tests

---

romancal/ramp_fitting/tests/test_ramp_fit.py

Closes #
Resolves RCAL-106
Initial version of ramp fitting unit tests for Roman, ONLY for the purpose of beginning this PR. This version has a single test which is marked to XFAIL. Later versions will have the complete suite of several dozen tests enabled to run. This PR supersedes PR#329.
This PR addresses ramp_fitting unit tests for Roman.
Checklist
- [ X] Tests

Add unit tests for roman ramp fit (RCAL-106)

---

CHANGES.rst
romancal/regtest/conftest.py
romancal/stpipe/core.py
romancal/stpipe/tests/test_core.py
setup.cfg

Resolves RCAL-244
This PR uses a new feature in stpipe to access log messages from the step/pipeline and record them in ImageModel.cal_logs.  Depends on the following dependency PRs:
https://github.com/spacetelescope/stpipe/pull/35
https://github.com/spacetelescope/rad/pull/96
https://github.com/spacetelescope/roman_datamodels/pull/53
Here's an example cal_logs array:
```yaml
cal_logs: !<asdf://stsci.edu/datamodels/roman/tags/cal_logs-1.0.0>
- '2021-11-17T19:45:16.299Z :: stpipe.LoggingStep :: INFO :: Step LoggingStep running
with args ().'
- '2021-11-17T19:45:16.300Z :: stpipe.LoggingStep :: INFO :: Step LoggingStep parameters
are: {''pre_hooks'': [], ''post_hooks'': [], ''output_file'': None, ''output_dir'':
None, ''output_ext'': ''.asdf'', ''output_use_model'': False, …
```

Record step/pipeline logs in ImageModel.cal_logs

---

CHANGES.rst
romancal/flatfield/flat_field.py
romancal/flatfield/tests/test_flatfield.py

Closes #363 
Resolves RCAL-253 Add a check for exposure type for the FlatField Step
This PR adds a check for WFI_Image in flat field step, and skips the step (with appropriate calstep update) if a different exposure type. Test of this is also added.
Checklist
- [x ] Tests

Skip Flatfield For Non-Image Exposure Types

---

CHANGES.rst
romancal/regtest/test_ramp_fitting.py

Closes #369
Resolves RCAL-254
This PR addresses fixes the naming for the output files for the regression testing. 
Checklist
- [x ] Tests
- [x ] Documentation

RCAL-254 Update ramp fit regression tests

---

JenkinsfileRT

the number of pytest jobs is hard coded at 30; changing it to 'auto' to properly scale with the build server's resources

remove hard-coded config for number of test jobs

---

CHANGES.rst
romancal/regtest/test_dark_current.py

Closes #392
Resolves RCAL-186
This PR adds an initial set of dark current regression tests. The test for the option --dark_output is currently xfailed and the ticket RCAL-285 is filed to address that failure. Once this is fixed the test should be reinstated. 
Checklist

RCAL-186 Add regression tests for Dark Current Step

---

CHANGES.rst
romancal/regtest/test_linearity.py

Closes #394
Resolves RCAL-268
This PR adds regression tests for Linearity correction
results from local pytest,
...
-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========== 2 passed, 15 deselected, 2 warnings in 743.94s (0:12:23) ===========
Checklist

RCAL-268 Regression tests for Linearity correction

---

JenkinsfileRT

SPB-778 Added a failure threshold so that failed regressions do not trigger an update during the build process
Resolves RCAL-
Checklist

SPB-778 Bugfix: Romancal dependency uploads occuring with failed regressions

---

CHANGES.rst
pytest.ini
romancal/regtest/test_jump_det.py

GitHub issue, Closes #409
Resolves RCAL-292
This PR updates the jump regression test input parameter to reduce the runtime. The parameters are
-steps.jump.rejection_threshold=180. 
--steps.jump.three_group_rejection_threshold=185. 
--steps.jump.four_group_rejection_threshold=190.
Running the local regression tests with the updated parameters, 
pytest --bigdata ~/src/Roman/romancal/romancal/regtest/ --basetemp=/Users/ddavis/src/Roman/develop/test/tmp_tc/ \
-k jump  2>&1 | tee regression_test_Jan21_01.log
============================= test session starts ==============================
platform darwin -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/ddavis/src/Roman/romancal, configfile: pytest.ini
plugins: arraydiff-0.3, asdf-2.8.1, remotedata-0.3.2, …

Rcal 292 Update regression test inputs parameters to reduce runtime

---

.codecov.yml
tox.ini

Resolves RCAL-
This PR updates the tox matrix to use the updated numpy versions (PR 414), dropping numpy 1.18 and adding numpy 1.20
Adds .codecov.yml to have our code coverage more stable (following JWST). 
Checklist

Add .codecov.yml to repository

---

JenkinsfileRT

This PR addresses a potential security issue in the Jenkins file with
groovy string interpolation of variables. Groovy treats "double quoted"
strings in a slightly different way from "single quoted" strings.
A warning was raised in the Jenkins run of the regression tests.

fix string interpolation in Jenkins file

---

CHANGES.rst
romancal/lib/dqflags.py
romancal/regtest/regtestdata.py
setup.cfg

GitHub issue, Closes #175
Resolves [RCAL-nnnn](https://jira.stsci.edu/browse/RCAL-nnnn) N/A
This PR updates the PEP8 checks to be inline with what JWST does, c.f. 
https://github.com/spacetelescope/jwst/pull/5805
https://github.com/spacetelescope/jwst/pull/5812
Most of these were already in place and but E241 & E704 were added.
The file romancal/lib/dqflags.py is excluded from the check to maintain readability,
with the check in place it looks like a hot mess.  
Currently 
bash>flake8 romancal/
0
Checklist

GH issue 175 Update PEP 8 checks

---

docs/conf.py

This PR addresses the location change of the scipy and numpy intersphinx inventory files which was causing documentation build  errors. 
Checklist

Update intersphinx documentation URLs for numpy and scipy

---

CHANGES.rst
romancal/dark_current/dark_current_step.py
romancal/regtest/test_dark_current.py

GitHub issue, Closes #406 
Resolves [RCAL-285](https://jira.stsci.edu/browse/RCAL-285)
This PR fixes dark_current subtraction step with the optional --dark_output.
Checklist

RCAL-285 dark current subtraction output file fails

---

CHANGES.rst
romancal/dq_init/dq_init_step.py
romancal/dq_init/tests/test_dq_init.py
romancal/ramp_fitting/ramp_fit_step.py

The dq_init step copies the original 3D border reference pixels and their dq arrays into individual attributes. The ramp fitting step trims the border pixel arrays from the science data/dq/err arrays.

RCAL-308 Update the output of dq_init and ramp_fitting for reference pixel correction

---

CHANGES.rst
docs/roman/package_index.rst
docs/roman/photom/index.rst
docs/roman/photom/reference_files.rst
docs/roman/references_general/area_reffile.inc
docs/roman/references_general/area_selection.inc
docs/roman/references_general/dark_reffile.inc
docs/roman/references_general/photom_reffile.inc
docs/roman/references_general/photom_selection.inc
docs/roman/references_general/references_general.rst

GitHub issue, Closes #173 
Resolves [RCAL-129](https://jira.stsci.edu/browse/RCAL-129)
This PR addresses adding documentation for PHOTOM and Area reference files, which required placeholder documentation for the photom step. In addition, I fixed an improper object in dark documentation.
Checklist

RCAL-129: Document photom & area reference files

---

CHANGES.rst
docs/index.rst
docs/roman/error_propagation/index.rst
docs/roman/error_propagation/main.rst
setup.cfg

GitHub issue, Closes #20 
Resolves [RCAL-nnnn](https://jira.stsci.edu/browse/RCAL-46)
This PR addresses adds documentation for the error propagation in the ELPP pipeline. 
Currently we have definitions for the errors in ramp fitting and the flat field steps. The
code changes were in other issues. 
Also bump astropy >=5.0.4
Checklist

Rcal 46 Initial documentation for error propagation

---

romancal/saturation/saturation.py
setup.cfg

A new parameter to control the flagging of pixels adjacent to saturated pixels was added to stcal [#83]. This PR just maintains NOT flagging adjacent pixels - the tests need to be modified for this and it's needed for JWST, so it can be added later.

new param for saturation, continute to not flag adjacent pixels for now

---

CHANGES.rst
romancal/photom/photom_step.py
romancal/photom/tests/test_photom.py

GitHub issue, Closes #497 
Resolves [RCAL-339](https://jira.stsci.edu/browse/RCAL-339)
This PR allows the photometric constants for spectroscopic data to remain as None as 
we agreed to with INS. 
Checklist
- [N/A] Documentation

RCAL-339 Update photom step to skip spectroscopic data

---

CHANGES.rst
romancal/saturation/saturation.py
setup.cfg

…n STCAL.
Resolves [JP-374](https://jira.stsci.edu/browse/JP-374)
The ticket JP-374 got merged into STCAL, but changed a saturation function signature causing failures in romancal.  The function signature in romancal has been updated and the saturation unit tests pass.
Checklist

JP-374: ZEROFRAME processing to STCAL changed function signatures.

---

CHANGES.rst
romancal/flatfield/flat_field.py
romancal/flatfield/flat_field_step.py
romancal/regtest/test_jump_det.py
romancal/regtest/test_ramp_fitting.py
romancal/regtest/test_wfi_dq_init.py
romancal/regtest/test_wfi_flat_field.py
romancal/regtest/test_wfi_photom.py
romancal/regtest/test_wfi_pipeline.py
romancal/regtest/test_wfi_saturation.py

GitHub issue, Closes #502 
Resolves [RCAL-340](https://jira.stsci.edu/browse/RCAL-340)
This PR updates to flat field code to handle the case of grism observations with no flat field reference files and removes the skip so that DMS-86, 87, 90, & 91 are covered. 
The results of the regression tests can be found at
https://plwishmaster.stsci.edu:8081/me/my-views/view/all/job/RT/job/Roman-Developers-Pull-Requests/12/
Checklist

Rcal-340 Updates to flat field code to handle no flat for grism data & remove skip

---

CHANGES.rst
romancal/photom/photom.py
romancal/photom/tests/test_photom.py

Resolves [RCAL-346](https://jira.stsci.edu/browse/RCAL-346)
This PR explicitly test that photometric keywords are populated with none for GRISM, PRISM, and DARK.
Checklist

Rcal 346 spec photom

---

CHANGES.rst
romancal/assign_wcs/assign_wcs_step.py
romancal/assign_wcs/tests/test_wcs.py

GitHub issue, Closes #462
Resolves [RCAL-319](https://jira.stsci.edu/browse/RCAL-319)
Adds distortion transform to `assign_wcs`
Checklist

Add distortion transform to assign_wcs

---

CHANGES.rst
romancal/dq_init/dq_init_step.py
romancal/flatfield/flat_field_step.py

GitHub issue, Closes #478 
Resolves [RCAL-330](https://jira.stsci.edu/browse/RCAL-330)
This PR simplified reference file name and model storage in dq and flat steps. (Changing them from lists to single variables and removing the list traversal code.)
Checklist

RCAL-330: Change Reference Datamodel Storage Type in Steps

---

CHANGES.rst
JenkinsfileRT
JenkinsfileRT_dev
requirements-dev.txt
requirements-sdp.txt
romancal/assign_wcs/assign_wcs_step.py
romancal/dark_current/dark_current_step.py
romancal/dq_init/dq_init_step.py
romancal/flatfield/flat_field_step.py
romancal/flatfield/tests/test_flatfield.py
romancal/jump/jump_step.py
romancal/lib/suffix.py
romancal/linearity/linearity_step.py
romancal/photom/photom_step.py
romancal/ramp_fitting/ramp_fit_step.py
romancal/regtest/test_dark_current.py
romancal/regtest/test_jump_det.py
romancal/regtest/test_linearity.py
romancal/regtest/test_ramp_fitting.py
romancal/regtest/test_wfi_dq_init.py
romancal/regtest/test_wfi_flat_field.py
romancal/regtest/test_wfi_photom.py
romancal/regtest/test_wfi_saturation.py
romancal/saturation/saturation_step.py

GitHub issue, Closes #455
Resolves [RCAL-310](https://jira.stsci.edu/browse/RCAL-310)
This PR updates the suffix utility to replace the file suffix with the suffix appropriate for the given step. Updates the step code to create the correct suffix when needed and updates the regression tests and the reference data in artifactory to reflect the new names. 
Unit tests passing: 
pytest ~/src/Roman/romancal/romancal
======================================================== test session starts ========================================================
platform darwin -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/ddavis/src/Roman/romancal, configfile: pytest.ini
plugins: xdist-2.5.0, remotedata-0.3.3, forked-1.4.0, astropy-header-0.2.1, mock-3.7.0, astropy-0.10.0, …

rcal-310 Update code to update suffixes, update regtests for the new names

---

romancal/assign_wcs/assign_wcs_step.py
romancal/assign_wcs/tests/test_wcs.py

Resolves [RCAL-295](https://jira.stsci.edu/browse/RCAL-295)
This PR addresses the creation of a detector's `S_REGION`. We use the same approach used by JWST to calculate the aperture's footprint from WCS. The result is saved under `meta.wcsinfo`.
A simple test was also implemented inside of `test_wcs.py` that verifies if the length and format of `S_REGION` are in accordance with the expectation. We also check for a $\le$ 10% accuracy between the `S_REGION` results and the ICRS reference coordinates for the aperture.
@ddavis-stsci to review.
_N.B._: There is a discrepancy in the footprint results that we get for our simulated images (based on the telescope pointing and WCS info available in the metadata) and the ones that we get from [this …

Rcal 295 compute s region

---

.github/workflows/roman_ci.yml
CHANGES.rst
setup.cfg

The `numpy` version defined at https://github.com/spacetelescope/romancal/blob/58937f347aef7019d8c93884d9ce04f7caa244ae/setup.cfg#L29 causes version conflicts when testing older `numpy` versions in `romancal` unit tests: https://github.com/spacetelescope/romancal/pull/511#issuecomment-1179176360.
However, it does not seem that this version requirement is necessary; as the checks introduced by this PR show, multiple older versions of `numpy` pass unit tests. 
Is there a reason to pin `numpy` to this version? Also, can these be tested in regression tests as well?
**blocked by https://github.com/spacetelescope/roman_datamodels/pull/84**
**Checklist**

release `numpy` requirement

---

CHANGES.rst
romancal/stpipe/core.py

Resolves [RCAL-332](https://jira.stsci.edu/browse/RCAL-332)
Checklist

RCAL-332 populate meta.ref_file

---

.github/labeler.yml
.github/workflows/label_pull_request.yml

This GitHub workflow runs a labeler action on new / edited pull requests that scans the filenames of changed files and applies relevant labels. This process is configured in `.github/labeler.yml`, which I copied and modified from https://github.com/spacetelescope/jwst/pull/6933
An example of this labeler working can be seen here: https://github.com/spacetelescope/stsynphot_refactor/pull/153
**Checklist**

automatically add labels to pull requests based on changed files

---

CHANGES.rst
romancal/pipeline/exposure_pipeline.py

The variable `input_filename` was only being assigned if the input to ExposurePipeline was a string, but it was being checked so inputting a model wasn't working.

fix input file

---

romancal/dq_init/tests/test_dq_init.py
romancal/photom/tests/test_photom.py

This PR fixes `flake8` warnings (`E275 missing whitespace after keyword`).
**Checklist**

fix `flake8` warnings

---

romancal/regtest/test_wfi_photom.py

Closes #
This PR updates some photom parameters and artifactory files for test_wfi_photom.py
and now,
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========== 1 passed, 18 deselected, 1 warning in 802.56s (0:13:22) ============
**Checklist**

Fix photom test

---

.gitignore
CHANGES.rst
romancal/regtest/test_wfi_pipeline.py

Resolves [RCAL-364](https://jira.stsci.edu/browse/RCAL-364)
Closes #
This PR adds tests for SOC-587: "_in Wide Field Imaging mode, the DMS shall generate Level 2 science data products that incorporate information needed to correct for pixel geometric distortion._"
For the time being, the test checks if `AssignWcsStep` is complete and if a WCS object has been created. Although not necessarily needed, we should also check if a distortion reference file was used by checking `meta.ref_file['distortion']`. This will be implemented soon after checking if the pipeline updates `meta.ref_file` with the reference file used after each step.
**Checklist**

Add tests for SOC-587.

---

.github/workflows/publish-to-pypi.yml

This PR applies fixes to the `check` job (that checks `requirements-sdp.txt`) on release. For some reason, the existing `&&` syntax doesn't work in the `bash` shell on `ubuntu-latest`, but this `if` block does. 
This change is related to the analogous JWST PR https://github.com/spacetelescope/jwst/pull/7060
**Checklist**

Fix requirements check

---

.github/workflows/roman_ci.yml
CHANGES.rst
setup.cfg

Resolves [SCSB-52](https://jira.stsci.edu/browse/SCSB-52)
`astropy` is updating its `numpy` requirement to `1.20`, resulting in failures in CI jobs testing older `numpy` versions (https://github.com/spacetelescope/romancal/actions/runs/3311427058/jobs/5467138563).
Related to https://github.com/astropy/astropy/pull/13885
**Checklist**

up `numpy` requirement to `1.20`

---

CHANGES.rst
romancal/photom/photom_step.py

Resolves [RCAL-419](https://jira.stsci.edu/browse/rcal-419)
Closes #
This PR updates photom to use the default suffix when processing prism and grism data. 
**Checklist**

RCAL-419 Update photom to use default suffix for spectral data

---

CHANGES.rst
romancal/dq_init/dq_init_step.py
romancal/dq_init/tests/test_dq_init.py
romancal/lib/dqflags.py

Resolves [RCAL-402](https://jira.stsci.edu/browse/JP-402)
Closes #579 
This PR adds flagging for science data that is affected by the guide window reads and have enhanced noise. The flag is 'GW_AFFECTED_DATA': 2**4
**Checklist**

Rcal-402 Add Flags for science data affected by guide window reads

---

.github/workflows/roman_ci.yml
CHANGES.rst
setup.cfg
tox.ini

This PR turns the existing dependent-workflow structure back into `tox`, and caches CRDS data for the same operational context, so it is not downloaded every time. This functionality is not currently useful (it is skipped currently) but will become useful when Roman CRDS becomes publicly available.
**Checklist**

use `tox` and set up CRDS caching when server is accessible

---

.github/workflows/roman_ci.yml
JenkinsfileRT
tox.ini

This PR adds tracers for Datadog
This is a copy of #606 , moved here to ensure that the CI tests have access to the `DD_API_KEY` organizational secret
It appears that Datadog requires CI runs to be run against the main branch in order to show on the dashboard
**Checklist**

add Datadog CI agent

---

.github/workflows/roman_ci.yml

This PR addresses the issue where PRs from forks cannot run because they don't have access to the `DD_API_KEY` organizational secret.
Hotfix for #615 
**Checklist**

[hotfix] fix CI on PRs from forks

---

CHANGES.rst
pyproject.toml
romancal/conftest.py

resolves [SCSB-53](https://jira.stsci.edu/browse/SCSB-53)
This PR addresses the Pytest deprecations introduced in 7.2 ahead of the 8.0 release.
**Checklist**

fix deprecation warnings ahead of Pytest 8.0

---

.github/workflows/roman_ci.yml

This PR widens the branch trigger for CI workflow runs, ensuring that release branches with a trailing `x` are always tested.
**Checklist**

fix branch filter to trigger on release branches

---

.github/workflows/roman_ci.yml

This PR addresses the lack of CI runs in the `TEST RUNS` section of Datadog
**Checklist**

add environment variables to Datadog run

---

CHANGES.rst
romancal/jump/jump_step.py

Resolves [RCAL-460](https://jira.stsci.edu/browse/rcal-460)
Closes #
This PR addresses updates the default jump CR rejection threshold to give "reasonable" run times and approximately the correct number of cosmic rays. This is a known issue with the code in common with JWST and the JWST team is looking at why the parameters are not working as expected. We will adopt their solution once available. 
**Checklist**

RCAL-460 Update default CR rejections in jump_step

---

CHANGES.rst
romancal/regtest/test_wfi_pipeline.py

Resolves [RCAL-479](https://jira.stsci.edu/browse/rcal-479)
Closes #
This PR adds tests for the PSF determination as described in, [Build 9 Planning](https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=ROMAN&title=Build+9+requirements+and+test+planning) SOC-565 Success Criteria:
We test for detector and optical_element in the final level 2 file. 
The regression tests are passing and can be seen at,
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/96/
**Checklist**

RCAL-479 Test for PSF keywords (DMS-136)

---

docs/roman/datamodels/datamodels_asdf.rst
pyproject.toml
pytest.ini
romancal/associations/registry.py

remove pytest.ini
The existence of pytest.ini (introduced in https://github.com/spacetelescope/romancal/pull/411) prevented pytest from
reading options from pyproject.toml that for one
example disabled doctests
~~I'm expecting this will fail ci as at least one doctest contains a use of jwst:~~ Edited: fixed this reference
https://github.com/spacetelescope/romancal/blob/393d60f4702489d9e1d2f8b1fa7054e678b619b2/romancal/associations/registry.py#L63
which appears as a failure in the stpipe downstream ci testing of romancal:
https://github.com/spacetelescope/stpipe/actions/runs/4161774078/jobs/7200153620#step:8:39
**Checklist**

move pytest markers to pyproject.toml

---

CHANGES.rst
pyproject.toml

`ruff` is an in-development Python linter written in Rust that aims for rule-checking parity with Flake8 and Black: https://github.com/charliermarsh/ruff
It has several advantages over `flake8`, including significant speedups in linting and support for `pyproject.toml` configuration and PEP517 / PEP621.
**Checklist**

use `ruff` in place of `flake8`

---

romancal/tweakreg/tweakreg_step.py

This PR addresses a bug in `TweakReg` where an ASDF object was being closed prematurely.
The object was being closed while `TweakReg` was determining the common name of the ASDF files in the input list.
**Checklist**

Bug fix: make sure ASDF is not closed prematurely.

---

romancal/tweakreg/tweakreg_step.py

This PR addresses the case when the user wants to run TweakRegStep without running source detection first.
In addition to creating an output file with the results, the source detection step adds an attribute (`tweakreg_catalog`) to the `meta` indicating the filename that should be used in `TweakRegStep` for alignment with Gaia. Such attribute will always be present when the romancal pipeline is executed through the `ExposurePipeline` class.
In the case where the user wants to execute TweakRegStep separately without first running source detection, then `tweakreg_catalog` will be missing. For now, we will only raise an `AttributeError` and stop processing.
**Checklist**

Raise exception whenever tweakreg_catalog is missing.

---

CHANGES.rst
pyproject.toml
romancal/assign_wcs/tests/test_wcs.py
romancal/dark_current/dark_current_step.py
romancal/dark_current/tests/test_dark.py
romancal/dq_init/dq_init_step.py
romancal/dq_init/tests/test_dq_init.py
romancal/flatfield/tests/test_flatfield.py
romancal/jump/tests/test_jump_step.py
romancal/photom/tests/test_photom.py
romancal/ramp_fitting/ramp_fit_step.py
romancal/ramp_fitting/tests/test_ramp_fit.py
romancal/saturation/tests/test_saturation.py
romancal/stpipe/tests/test_core.py

Resolves [RCAL-486](https://jira.stsci.edu/browse/JP-nnnn)
Closes #
This PR addresses changes in the location of datamodel maker utilities in RDM.
**Checklist**

RCAL-486: Update Maker Utlity Imports

---

romancal/source_detection/tests/test_source_detection_step.py

When I ran the unit tests locally, this test:
https://github.com/spacetelescope/romancal/blob/dec39b6fc756a49cff18c1bcf2a5ad650037c1d1/romancal/source_detection/tests/test_source_detection_step.py#L159-L185
started failing the checks for the created file.
This was caused by the step not being run in the temporary directory created for the test. This left the file behind after the test finished and the test for the output file was with respect to this directory. This PR fixes this bug by using a context manager to temporarily change python's working directory to the test's temporary directory for the duration of the test.
The reason this was not caught by the CI in #608 is because this test is not run by the GitHub CI at this time due to the lack of a public CRDS server.
**Checklist**

Bugfix for source_detection's test_outputs

---

CHANGES.rst
pyproject.toml

Resolves [RCAL-481](https://jira.stsci.edu/browse/RCAL-481)
`pytest-openfiles` has been deprecated and is interfering with the use of fixtures in our test code (ones that handle files). This PR switches `ResourceWarnings` into errors which will catch almost all cases of files left open. The only cases it does not catch is if an open file handle is assigned to a global variable as the "warning" will not be emitted until python stops running, which occurs after pytest has completed. 
**Checklist**

RCAL-481: Remove use of pytest-openfiles

---

CHANGES.rst
romancal/source_detection/tests/test_source_detection_step.py

Closes https://github.com/spacetelescope/romancal/issues/667
Randomness in tests for source detection was causing them to intermittently fail. Tests now use np.random.seed(0) by default, and have an option to change or not use this seed. 
**Checklist**

add seed for random noise/gaussian generation in tests

---

CHANGES.rst
JenkinsfileRT
pyproject.toml

The `codecov-python` (`codecov` dependency) uploader has been deprecated for some time and now it has been yanked from PyPi. This means installing `romancal` with the `test` dependencies will no-longer succeed. The `codecov` dependency was only used by the regression tests to upload coverage of the regression tests, this has been replaced by the new non-python-based `codecov-uploader` in just the regression test jobs.
**Checklist**

Remove `codecov` test dependency

---

CHANGES.rst
docs/roman/package_index.rst
docs/roman/pipeline_steps.rst
docs/roman/tweakreg/README.rst
docs/roman/tweakreg/astrometric_utils.rst
docs/roman/tweakreg/index.rst
docs/roman/tweakreg/tweakreg_examples.rst
docs/roman/tweakreg/tweakreg_step.rst
pyproject.toml
romancal/conftest.py
romancal/tweakreg/astrometric_utils.py
romancal/tweakreg/tests/test_astrometric_utils.py
romancal/tweakreg/tests/test_tweakreg.py
romancal/tweakreg/tweakreg_step.py

Resolves [RCAL-527](https://jira.stsci.edu/browse/RCAL-527)
This PR addresses updates to the RomanCal version of TweakReg.
**Checklist**

TweakReg: doc updates.

---

JenkinsfileRT
JenkinsfileRT_dev

Resolves [SCSB-63](https://jira.stsci.edu/browse/SCSB-63)
This PR addresses the issue where override requirements were overridden themselves during the Jenkins regression test build.
Related to https://github.com/spacetelescope/jwst/pull/7553
**Checklist**
- [N/A] ~added entry in `CHANGES.rst` under the corresponding subsection~

SCSB-63 inject dependency overrides after build

---

CHANGES.rst
romancal/source_detection/source_detection_step.py

Small fix to ensure that a catalog is only attached to the output model if save_catalogs=False.

fix output catalog attribute

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml

This PR uses the new `pytest-results-summary` keyword in the OpenAstronomy reusable workflow to display test summaries on the job page:
If tests fail, the [`test-summary` action](https://github.com/marketplace/actions/testforest-dashboard) will create a Markdown table of failures:
**Checklist**
- [N/A] ~added entry in `CHANGES.rst` under the corresponding subsection~
- [N/A] ~updated relevant documentation~
- [N/A] ~updated relevant milestone(s)~

enable step summary for pytest results

---

requirements-dev.txt

Related to [SCSB-69](https://jira.stsci.edu/browse/SCSB-69)
This PR ensures that `astropy`, `scipy`, and `numpy` are all built with nightly wheels against `main`
**Checklist**

test against nightly builds of `astropy`, `scipy`, and `numpy`

---

JenkinsfileRT
pyproject.toml
romancal/regtest/test_wfi_pipeline.py

Closes #692 
This PR upgrades python to 3.11, updates the CRDS context to 0043, and fixes some spelling and message syntax issues. 
The regression tests can be found at https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/902/
for the unit tests
python --version
Python 3.11.0
= 363 passed, 22 skipped, 6 warnings in 135.82s
```
pytest ~/src/Roman/romancal/romancal/
=================================================================== test session starts ===================================================================
platform darwin -- Python 3.11.0, pytest-7.3.1, pluggy-1.0.0
plugins: remotedata-0.4.0, hypothesis-6.75.1, asdf-2.15.0, mock-3.10.0, …
```

Upgrade romancal python to python-3.11, update crds context

---

romancal/tweakreg/tests/test_tweakreg.py

spacetelescope/roman_datamodels#164 generalizes the `ModelContainer` constructor, which causes a single test in tweakreg to fail because it expects a different error type when `TweakRegStep.call` is called with incorrect arguments. 
This PR changes the tweakreg test to check that the failure is one of two types – the first error is the expected error after spacetelescope/roman_datamodels#164 is merged, the second error is the old expected error. This test should pass whether the current rdm version is before or after spacetelescope/roman_datamodels#164 gets merged.
**Checklist**

Compatibility fix in tweakreg test for rdm#164

---

CHANGES.rst
romancal/tweakreg/astrometric_utils.py
romancal/tweakreg/tests/test_astrometric_utils.py
romancal/tweakreg/tests/test_tweakreg.py
romancal/tweakreg/tweakreg_step.py

Resolves [RCAL-561](https://jira.stsci.edu/browse/RCAL-561)
This PR adds a `try-except` block in `TweakReg` to handle errors when fetching data through `astrometric_utils.get_catalog`, which now has three additional exception catches (all subclasses of `requests.exceptions.RequestException`):
- `ConnectionError` (not able to connect to the VO API server);
- `TimeOut` (service timeout);
- `RequestException` (any other exception raised specifically by `requests`).
Each one has its own specific error message to help with debugging.
If `TweakRegStep` cannot create an absolute reference catalog (in cases where the VO API server is not available), then we'll do the default in situations where the step cannot proceed:
- print a warning message in the logs;
- set the class instance variable …

RCAL-561: improve error-handling for TweakReg when fetching data from VO API service.

---

CHANGES.rst
romancal/associations/main.py
romancal/tweakreg/tests/test_astrometric_utils.py

Resolves [RCAL-567](https://jira.stsci.edu/browse/rcal-567)
Closes #
This PR updates unit tests to add tmpdir for test files. 
Unit tests
pytest /Users/ddavis/src/Roman/romancal/romancal/associations/tests/
=================================================================== test session starts ===================================================================
platform darwin -- Python 3.11.0, pytest-7.3.1, pluggy-1.0.0
...
============================================================== 55 passed, 1 skipped in 0.98s
ls *.json
ls: *.json: No such file or directory
pytest /Users/ddavis/src/Roman/romancal/romancal/tweakreg/tests/
=================================================================== test session starts …

RCAL-567 Update unit tests to add tmpdir for test files

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml

Closes #
This PR updates the CRDS server from  https://roman-crds.stsci.edu/ to 
https://roman-crds-test.stsci.edu/  so that the latest context will be selected for testing. This is currently at roman_0047.pmap for the 23Q3_B10 release. 
**Checklist**

Update roman crds server to test so that the latest updates are used

---

.github/workflows/roman_ci.yml

This PR addresses 2 issues:
1. I have begun to notice 143 errors with our CI. This is due to over use of action runner resources, which I believe is related to using too much memory. This memory issue is simply because `xdist` will be running multiple tests simultaneously which eats up too much memory under certain conditions.
2. The titles of the CI runs in GitHub are not very distinguishable. This PR updates them to make them more clear.
This PR is similar to spacetelescope/roman_datamodels#187.
Note the "required" CI in the branch protections will likely need to be updated after this PR is merged.
**Checklist**

Update the CI

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml

This PR adds a trigger label to run the weekly CI as part of a PR, and removes a few extra xdist I missed in #706
**Checklist**

More CI updates

---

CHANGES.rst
romancal/source_detection/source_detection_step.py

Resolves [RCAL-562](https://jira.stsci.edu/browse/RCAL-562)
This PR addresses a fix to `SourceDetectionStep` to return an **open datamodel** object with all the changes made in the source detection step.
Regression test result:
- https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/188/
**Checklist**

Fix returned result from SourceDetectionStep.

---

CHANGES.rst

PR #687 put its change log entry in an already released version. This PR simply moves it to the correct place.
**Checklist**

Move skymatch changelog entry to correct version

---

JenkinsfileRT
JenkinsfileRT_dev

Currently the pip freeze happens after the initial dependency install, but before the OVERRIDE_REQUIREMENTS option is handled by Jenkins. This makes it difficult to see if Jenkins has successfully installed an overriden requirement for the test run. This PR adds an additional `pip list` (same as `pip freeze` just more nicely formatted as a table) after the OVERRIDE_REQUIREMENTS are applied so that one can check in the Jenkins job log to make sure overriden requirements have successfully installed.
**Checklist**

Add a `pip list` step after the overrides are injected

---

CHANGES.rst
romancal/datamodels/container.py
romancal/lib/basic_utils.py
romancal/tweakreg/tweakreg_step.py

The [`is_association`](https://github.com/spacetelescope/roman_datamodels/blob/f6c990530f7ed24afbc4744f8dcdecd81c832b6e/src/roman_datamodels/util.py#L312-L319) function, while part of `roman_datamodels` is not used or tested anywhere in `roman_datamodels`. Indeed, it seems to be part of a module which partially duplicates parts of `romancal.lib`. Thus it makes sense to move this into `romancal` directly alongside all the functionality which has been duplicated.
**Checklist**

Move `is_assocation` to `romancal`

---

romancal/assign_wcs/assign_wcs_step.py
romancal/assign_wcs/tests/test_wcs.py
romancal/tweakreg/tests/test_astrometric_utils.py
romancal/tweakreg/tests/test_tweakreg.py

This PR fixes a typo issue in the `S_REGION` string.
**Checklist**

Fix typo in S_REGION string.

---

CHANGES.rst
romancal/dark_current/tests/test_dark.py
romancal/dq_init/dq_init_step.py
romancal/dq_init/tests/test_dq_init.py
romancal/flatfield/tests/test_flatfield.py
romancal/jump/tests/test_jump_step.py
romancal/ramp_fitting/tests/test_ramp_fit.py

This PR updates `romancal` so that it is compatible with spacetelescope/roman_datamodels#207. These updates are mostly due to the enforcement of keyword only arguments to the maker_utils. This change was done to unify the API across all the different maker_utils.
**Checklist**
Regression tests do pass https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/231/

Updates for maker_utils API changes

---

CHANGES.rst
pyproject.toml
romancal/jump/jump_step.py

stcal recently updated jump detection and ramp fitting.
https://github.com/spacetelescope/stcal/releases/tag/1.4.0
This PR only addresses the jump detection changes (which changed the number of returned values).
The new returned values are ignored in this PR to fix the errors introduced by these changes.
I am not familiar with the arguments or return values for this function so a check for validity (and not just relying on a lack of failures) is needed.
**Checklist**
Regression tests run (against stcal main which is now released):
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/257/pipeline/206/

update jump detection for stcal changes

---

CHANGES.rst
romancal/ramp_fitting/tests/test_ramp_fit.py

Resolves [RCAL-604](https://jira.stsci.edu/browse/RCAL-604)
Closes #
This PR updates the ramp fitting unit tests for changes in stcal needed by JWST (JP-3242)
**Checklist**
```
pytest --pdb ~/src/Roman/romancal/romancal/ramp_fitting/tests/test_ramp_fit.py
=============================================================== test session starts ================================================================
platform darwin -- Python 3.11.0, pytest-7.3.1, pluggy-1.0.0
plugins: remotedata-0.4.0, env-0.8.1, asdf-2.15.0, mock-3.10.0, filter-subpackage-0.1.2, astropy-header-0.2.2, hypothesis-6.75.3, doctestplus-0.12.1, astropy-0.10.0, cov-4.0.0, ci-watson-0.6.1, openfiles-0.5.0, arraydiff-0.5.0
collected 9 items …
```

RCAL-604 update ramp fitting unit test for stcal 1.4.0

---

CHANGES.rst
romancal/assign_wcs/assign_wcs_step.py
romancal/dark_current/dark_current_step.py
romancal/flatfield/flat_field_step.py
romancal/linearity/linearity_step.py
romancal/saturation/saturation_step.py

Resolves [RCAL-432](https://jira.stsci.edu/browse/RCAL-432)
Closes #
This PR addresses updates the info strings to use the same syntax:
```
35:2023-06-23 10:36:29,154 - stpipe.ExposurePipeline.saturation - INFO - Using SATURATION reference file: /Users/ddavis/crds_cache/references/roman/wfi/roman_wfi_saturation_0229.asdf
41:2023-06-23 10:36:31,921 - stpipe.ExposurePipeline.linearity - INFO - Using LINEARITY reference file: /Users/ddavis/crds_cache/references/roman/wfi/roman_wfi_linearity_0215.asdf
45:2023-06-23 10:36:44,510 - stpipe.ExposurePipeline.dark_current - INFO - Using DARK reference file: /Users/ddavis/crds_cache/references/roman/wfi/roman_wfi_dark_0549.asdf
52:2023-06-23 10:36:47,012 - stpipe.ExposurePipeline.jump - INFO - Using GAIN reference file: …
```

RCAL-432 Update info string to use the same syntax

---

docs/conf.py

This PR removes the `myst_parser` from the docs as it is not needed. `sphinx-asdf` removed this the `myst_parser` recently.
**Checklist**

Remove myst parser from docs config

---

CHANGES.rst
docs/conf.py

Just like `roman_datamodels` search for the romancal docs is broken. @braingram suggested a fix for this in spacetelescope/roman_datamodels#227 which resolved this there. This PR makes the same change here. 
**Checklist**

Add jquery sphinx to fix doc search

---

CHANGES.rst
romancal/step.py
romancal/stpipe/integration.py

This PR registers `skymatch` with `stpipe` so that it can be run via the `strun` command.
**Checklist**

Register skymatch with stpipe

---

.github/workflows/changelog.yml

This PR updates the changelog CI to use the same changelog workflow used by `rad` and `roman_datamodels`. This workflow draws from an independent centralized workflow that has several additional features (including milestone verification if we wish to turn that on).
**Checklist**

Use same changelog workflow as the rest of the roman repositories

---

CHANGES.rst
pyproject.toml

This is a legacy option carried over from JWST. The option was part of a demonstration experiment for AWS from several years ago and was not properly removed from JWST/stdatamodels/stpipe until recently. Since the demonstration is long finished it should be removed here. See spacetelescope/jwst#7542, spacetelescope/stdatamodels#154, and spacetelescope/stpipe#91.
This PR removes this option as it is totally unused. 
**Checklist**

Remove AWS install option

---

CHANGES.rst
pyproject.toml

The spacetelescope/roman_datamodels#234 bumped the `roman_datamodels` min asdf dependency. This has broken the minimum dependencies CI. This PR bumps the dependency for `romancal` (which naturally will occur due to its strict dependency of `roman_datamodels`.
**Checklist**

Update asdf dependency

---

CHANGES.rst
JenkinsfileRT
JenkinsfileRT_dev
pyproject.toml

Resolves [RCAL-610](https://jira.stsci.edu/browse/RCAL-610)
Closes #783 
This PR addresses build errors when attempting to build the `ephem` extra
**Checklist**

remove unused extras

---

CHANGES.rst
romancal/dq_init/tests/test_dq_init.py
romancal/flatfield/tests/test_flatfield.py
romancal/jump/tests/test_jump_step.py
romancal/ramp_fitting/tests/test_ramp_fit.py
romancal/skymatch/tests/test_skymatch.py
romancal/source_detection/tests/test_source_detection_step.py

Closes #769
This PR transitions all the random number generation in romancal to be both deterministic and to use the recommend numpy [Random Generator](https://numpy.org/doc/stable/reference/random/generator.html) to control random number generation. All the random number generations are seeded so the tests are entirely reproducible.
**Checklist**

Make test randomness deterministic

---

CHANGES.rst
requirements-dev.txt
romancal/conftest.py

Currently, the Jenkins devdeps job is failing because something on the Jenkins machine has changed enough so that it can no longer build `astropy` wheels natively (some sort of compiler/base-library issue). Unlike the previous attempts at using the `astropy` nightly wheel this PR actually uses that wheel.
Also as a workaround to #793, this PR forces `numpy` 2.0.dev+ versions to use the legacy `numpy` 1.25 floating point (print) representation. Note that this will only work around this issue for the unit tests. ASDF will need to resolve this issue in order to have a general solution.
**Checklist**

Actually use the `astropy` nightly wheel.

---

CHANGES.rst
romancal/pipeline/exposure_pipeline.py
romancal/source_detection/source_detection_step.py
romancal/tweakreg/tweakreg_step.py

Resolves [RCAL-606](https://jira.stsci.edu/browse/RCAL-606)
Closes #765
This PR has the exposure pipeline and source detection and tweakreg steps skip processing if the data are not
WFI_IMAGE. 
**Checklist**
pytest romancal/source_detection/tests/
=============================================================== test session starts ================================================================
platform darwin -- Python 3.11.0, pytest-7.4.0, pluggy-1.2.0
plugins: remotedata-0.4.0, asdf-2.15.0, hypothesis-6.82.0, doctestplus-0.13.0, cov-4.1.0, filter-subpackage-0.1.2, mock-3.11.1, astropy-header-0.2.2, astropy-0.10.0, ci-watson-0.6.1, openfiles-0.5.0, env-0.8.2, arraydiff-0.5.0
collected 4 items …

rcal-606 Have source detection and tweakreg skip spectral data

---

romancal/conftest.py

In #795 a temporary hack to side step an issue ASDF was experiencing relative to the new `numpy` 2.0 changes was introduced to facilitate continued testing. This issue was fixed with the merger of asdf-format/asdf#1605. Since this issue is currently only experienced by the devdeps tests, this hack can be reverted. 
**Checklist**

Remove numpy 2.0 hack

---

CHANGES.rst
romancal/__init__.py
romancal/associations/pool.py

This PR removes the remaining usages of `pkg_resources` in `romancal` as `pkg_resources` has been [deprecated](https://grabcad.com/library/apple-magic-trackpad-2021-three-1) for some time in favor of the builtin `importlib` module.
**Checklist**

Remove usage of `pkg_resources`

---

CHANGES.rst
README.md
pyproject.toml

This PR adds a `dev` optional dependency install target for `romancal` which installs all of the tooling required to build the docs, run the tests, and/or run any of the CI test environments.
**Checklist**

Add dev optional dependency

---

.github/workflows/roman_ci.yml

It is sometimes useful to be able to manually trigger the github CI without a schedule or PR.
**Checklist**

Make it so we can manually trigger the CI

---

CHANGES.rst
romancal/datamodels/container.py
romancal/datamodels/tests/test_datamodels.py

Part of the purpose for `ModelContainer.get_crds_parameters` is so that `stpipe` can detect that a `ModelContainer` fits the description of a `DataModel` and that `stpipe` can then perform its actions on the `ModelContainer` object. It does this by checking the `ModelContainer` against: https://github.com/spacetelescope/stpipe/blob/6f84b52ffcce764a94806a35f5aefd28f3e8f8eb/src/stpipe/datamodel.py#L4-L68
However, this check only checks for the existence of these features: https://github.com/spacetelescope/stpipe/blob/6f84b52ffcce764a94806a35f5aefd28f3e8f8eb/src/stpipe/datamodel.py#L25-L29 not that they follow the template defined in `stpipe` in general.
Currently, `ModelContainer.get_crds_parameters` is defined as a property not a method which means it cannot be executed as a function. This …

Fix `get_crds_parameters` for `ModelContainer`

---

CHANGES.rst
romancal/ramp_fitting/ramp_fit_step.py

This PR addresses an issue where the `ramp_fit_step` was opening CRDS references files as read-write. This prevents use of a Central Store cache. Also, in principle, there is no reason to modify CRDS references.
**Checklist**
- ~updated relevant tests~
- ~updated relevant documentation~

fix opening mode for references to be read-only

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml
CHANGES.rst
pyproject.toml
requirements-dev.txt
romancal/lib/psf.py
romancal/lib/tests/test_psf.py
tox.ini

This PR introduces methods for fitting model PSFs computed with WebbPSF to ImageModels in romancal. 
Resolves [RCAL-573](https://jira.stsci.edu/browse/RCAL-573)
Closes #781
The model PSF is computed by `webbpsf`, and the model PSF is fit to Roman ImageModels using the new `photutils.psf` module refactor in https://github.com/astropy/photutils/pull/1558 (and futher PRs that followed it). I've pinned `photutils` to the dev version until the next release (expected within about a week), and pinned to the latest version of `webbpsf`.
Like CRDS, WebbPSF depends on several reference files which must be configured on a given machine before tests can be run. I've updated the CI setup so that GitHub Actions has access to those files. One limitation is that these WebbPSF reference files are …

PSF fitting methods

---

CHANGES.rst
romancal/lib/tests/test_psf.py

794 introduced PSF fitting methods, but one of the tests generated random sources without being reproducibly seeded, causing [some tests to fail](https://github.com/spacetelescope/romancal/actions/runs/6160941537/job/16719049660). This PR should fix it.
**Checklist**

PSF fitting random seed fix

---

.github/workflows/roman_ci.yml

`romancal` already uses the pre-commit.ci robot has part of its CI. This robot runs all of our style checks and reports if they pass or not in addition to offering autofixes for some style issues. The former is duplicated by the current `check-style` check, meaning that it is now unnecessary.
**Checklist**

Remove style check from CI

---

pyproject.toml
romancal/resample/resample_utils.py

PRs #771 and #862 were both made in order to cleanup our use of `numpy.random` so that our tests were more controllable, in particular #862  needed to fix intermittent failures due to "bad" random draws.
The `ruff` rule set [`NPY`](https://beta.ruff.rs/docs/rules/#numpy-specific-rules-npy), specifically has [`NPY002`](https://beta.ruff.rs/docs/rules/numpy-legacy-random/) which checks for use of the legacy NumPy randomness system, which is what was the heart of one was being corrected by #771 and #862. Additionally, its other rules will help us avoid some of the use of deprecated NumPy 2.0 functionality by automatically fixing the names of things to their non-deprecated name.
This PR adds the `NPY` rules to the rules being checked by `ruff` in order to help us avoid future randomness …

Add NumPy ruff rule set checking

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml

This PR addresses some issues with caching and using the output variables in the GitHub Actions workflow:
1. the `hashFiles` method apparently only works in the workspace, so attempting to hash `/tmp/data/` silently failed
2. the variable call used the old `crds` job name instead of `data`, so also silently failed
I didn't catch this issue when reviewing #794, but it should be fixed here
**Checklist**

fix caching and outputs

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml
.github/workflows/tests_devdeps.yml

Resolves [SCSB-79](https://jira.stsci.edu/browse/SCSB-79)
This PR reorganizes CI tests and moves devdeps tests to a new optional workflow that can be started with the label `run devdeps tests`
**Checklist**

reorganize tests, make devdeps testing optional, and unpin latest Python testing

---

CHANGES.rst
JenkinsfileRT

This PR addresses failing regression tests due to the new dependence on WebbPSF in the the PSF fitting methods introduced in #794. 
**Checklist**

Fix for failing regression tests from PSF fitting methods

---

.github/workflows/roman_ci.yml
JenkinsfileRT
JenkinsfileRT_dev
README.md
requirements-dev-st.txt
requirements-dev-thirdparty.txt
requirements-dev.txt
tox.ini

This PR splits the dev dependencies into `requirements-dev.txt` and `requirements-dev-thirdparty.txt`
**Checklist**

split `requirements-dev.txt` into first and third party dev dependencies

---

CHANGES.rst
romancal/pipeline/exposure_pipeline.py
romancal/refpix/refpix_step.py
romancal/regtest/test_refpix.py

Resolves [RCAL-647](https://jira.stsci.edu/browse/rcal-647)
Closes #883 
This PR adds the refpix step to the standard pipeline processing. It also has the refpix step update the cal_step attribute and uses the standard suffix "refpix" instead of the fallback of "refpixstep".
**Checklist**
The regression test is at https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/381
besides the known errors that are due to deepdiff, no other errors are seen.

RCAL-647 Update pipeline to include refpix step as default

---

CHANGES.rst
romancal/regtest/test_ramp_fitting.py
romancal/regtest/test_wfi_flat_field.py

Resolves [RCAL-681](https://jira.stsci.edu/browse/rcal-681)
Closes #909 
This PR updates reg tests for new algorithms and removal of the optional rampfit output of fitopt since the new ols_cas22 method does not save these. 
**Checklist**
All the regression tests now pass with the exception of the tweakreg tests, which need a new custom input file from INS.
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/390

rcal-681 Update reg tests for new algorithms

---

CHANGES.rst
romancal/regtest/regtestdata.py
romancal/regtest/test_regtestdata.py

`tweakreg_catalog` is now stored as an `astropy.table.Table`. This PR adds `astropy.table.Table` support to `compare_asdf` to allow regression tests to compare any `Table` instances (including `tweakreg_catalog`). This should fix tests that are failing with a reported difference that includes the `unprocessed` key (indicating that a portion of the items to being compared could not be processed due to lack of support for `Table` comparisons).
Regression tests all passed: https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/393/
**Checklist**

add astropy Table support to compare_asdf

---

CHANGES.rst
romancal/regtest/regtestdata.py
romancal/regtest/test_regtestdata.py

Provide ``atol`` to ``DeepDiff`` as ``math_epsilon`` argument to allow tolerancing scalar comparisons.
Drop use of ``astropy.utils.diff.values_differ`` as it does not provide readable output and does not allow control of ``nan`` equality. Instead, convert the table to a numpy structured array during comparison.
Add support for numpy structured array comparison.
Fixes https://github.com/spacetelescope/romancal/issues/916
**Checklist**
~Regression tests running at: https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/395/~
Regression tests are failing due to unavailable webbpsf data. https://github.com/spacetelescope/romancal/pull/918 fixes the issue for the regression tests.
EDIT: the url used to fetch the data appears to be back up (for now, box is having issues), …

update compare_asdf to use tolerance in more comparisons

---

.github/workflows/roman_ci.yml

This PR updates the url used for fetching webbpsf data to the most recent one in the webbpsf docs.
https://webbpsf.readthedocs.io/en/latest/installation.html#installing-the-required-data-files
Based off the comments and changes in https://github.com/spacetelescope/webbpsf/pull/739
the shared url for the webbpsf data used in this PR should (hopefully) stay up-to-date for future webbpsf data releases.
**Checklist**

update url for webbpsf data in github actions CI

---

CHANGES.rst
romancal/associations/generate.py
romancal/associations/lib/dms_base.py
romancal/associations/lib/rules_elpp_base.py
romancal/associations/lib/rules_level2.py
romancal/associations/tests/test_level2_basics.py
romancal/associations/tests/test_level2_candidates.py

Resolves [RCAL-641](https://jira.stsci.edu/browse/rcal-641)
Closes #851
This PR adds the ability to create the FOV associations with all 18 detectors from a single exposure available in PSS. 
**Checklist**
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/404/
The only failures are from tweakreg which this PR does not address

RCAL-641 Add FOV association generation

---

romancal/regtest/test_tweakreg.py
romancal/tweakreg/tests/test_astrometric_utils.py
romancal/tweakreg/tweakreg_step.py

This PR implements the following items to fix TweakReg's (TR) regression test:
- fix TR's catalog metadata: a bug was preventing the catalog metadata `name` from being properly set;
- updated the files used by TweakReg's regression test:
* input: `roman-pipeline/dev/WFI/image/r0000501001001001001_01101_0001_WFI02_cal_tweakreg.asdf`;
* truth: `roman-pipeline/dev/truth/WFI/image/r0000501001001001001_01101_0001_WFI02_tweakreg.asdf`.
The truth file in Artifactory was created by processing the cal file through the `TweakRegStep`:
```python
from romancal.stpipe import RomanStep
from romancal.tweakreg.tweakreg_step import TweakRegStep
step = TweakRegStep()
args = [
"romancal.step.TweakRegStep",
"/full/path/to/association/file/asn_filename.json",
"--output_file='tweakreg_truth_filename.asdf'", …
```

TweakReg regression test fix.

---

README.md

WebbPSF data is currently required to run unit tests; this PR adds instructions for making it accessible with the `WEBBPSF_PATH` environment variable.
**Checklist**

add instructions for downloading WebbPSF data

---

pyproject.toml
requirements-dev-st.txt
requirements-dev-thirdparty.txt

related to https://github.com/spacetelescope/roman_datamodels/pull/281; addresses potential issue where the resolver does not exactly match the dev dependencies, by making sure they all have `.git` suffixes and no branch specifier
**Checklist**

add `.git` to dev dependency specifications

---

CHANGES.rst
romancal/dark_current/tests/test_dark.py

Resolves [RCAL-693](https://jira.stsci.edu/browse/RCAL-693)
Closes #934
This PR removes the `err` array from Dark Current unit tests.
**Checklist**

RCAL-693: Removed err array from dark tests.

---

CHANGES.rst
romancal/regtest/regtestdata.py
romancal/regtest/test_regtestdata.py

When comparing 2 WCS objects in the deepdiff computed between the regtest result and truth file, use the array comparison options that are used for other arrays in the diff.
These changes will mean that if both the result and truth WCS objects return `nan` when evaluated on the bounding box (this is what's used to compare the two objects) that the WCS objects can be considered equal if both WCS objects return the same `nan`s.
**Checklist**
Running regression tests at: https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%252FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/426/

use ndarray comparison options in wcs comparison

---

CHANGES.rst
docs/conf.py
docs/roman/package_index.rst
docs/roman/pipeline_steps.rst
docs/roman/resample/arguments.rst
docs/roman/resample/index.rst
docs/roman/resample/main.rst
docs/roman/resample/resample.rst
docs/roman/resample/resample_step.rst
docs/roman/resample/resample_utils.rst
pyproject.toml
romancal/assign_wcs/assign_wcs_step.py
romancal/assign_wcs/utils.py
romancal/datamodels/container.py
romancal/lib/suffix.py
romancal/regtest/regtestdata.py
romancal/regtest/test_resample.py
romancal/resample/__init__.py
romancal/resample/gwcs_drizzle.py
romancal/resample/resample.py
romancal/resample/resample_step.py
romancal/resample/resample_utils.py
romancal/resample/tests/test_resample.py
romancal/resample/tests/test_resample_step.py
romancal/step.py
romancal/stpipe/integration.py

Resolves [RCAL-504](https://jira.stsci.edu/browse/RCAL-504)
This PR addresses the implementation of the resampling step in RomanCal.
**Notes**
This PR depends on [stcal's PR 196](https://github.com/spacetelescope/stcal/pull/196) (it uses the newly implemented `alignment` sub-package)
**Checklist**

Rcal 504 develop the resample step

---

JenkinsfileRT
JenkinsfileRT_dev

All regression tests are failing to upload results with the following error:
```
java.lang.RuntimeException: Failed uploading artifacts by spec
```
This is due to inclusion of `astroquery` as an indirect dependency (via `webbpsf`) which includes a test file `mission_results.json`:
https://github.com/astropy/astroquery/blob/5add2e3b0ff5b56630840a0f57196c19054f5c01/astroquery/mast/tests/data/mission_results.json#L5
which `jenkins_shared_ci` finds and treats as a test result file due to the currently configured search path (`root`).
This PR changes the `root` setting avoid inclusion of the `astroquery` file in the test results and allows the regression tests to pass the `Upload artifacts` step.
Thanks @BGannon2 for finding this fix!
Regression tests passed (with 1 known test failure: …

Fix regression test artifact upload

---

CHANGES.rst
romancal/tweakreg/tweakreg_step.py

Resolves [RCAL-688](https://jira.stsci.edu/browse/RCAL-688)
Closes #926
This PR fixes a bug in the `tweakreg` code due to which full unfiltered source catalog is being passed to `tweakwcs`. This PR makes sure that sources outside of the image's WCS bounding box are removed before the catalog is passed to `tweakwcs`.
**Checklist**

Filter catalog sources that are outside of the bounding box

---

CHANGES.rst
romancal/ramp_fitting/ramp_fit_step.py
romancal/ramp_fitting/tests/test_ramp_fit_cas22.py

This PR is intended to only make the necessary changes in `romancal` to support the Cas22 algorithm's interface changes introduced by spacetelescope/stcal#215 for the purposes of integrating jump detection directly into the the ramp fit itself. This PR is not intended to add support for the new jump detection algorithm, instead it is intended to resolve the minor interface changes introduced which break `romancal`. A follow on PR is planned to enable and test the new jump detection algorithm in `romancal`.
**Checklist**

Update Cas22 ramp fitting to integrate with the jump detection changes in stcal

---

CHANGES.rst
docs/roman/package_index.rst
docs/roman/ramp_fitting/arguments.rst
docs/roman/ramp_fitting/description.rst
docs/roman/ramp_fitting/description_ols.rst
docs/roman/ramp_fitting/index.rst

Resolves [RCAL-513](https://jira.stsci.edu/browse/RCAL-513)
Closes #
**Checklist**
- ~updated relevant tests~

RCAL-513 Update uneven ramp fitting documentation

---

CHANGES.rst
romancal/stpipe/core.py
romancal/stpipe/tests/test_core.py

Resolves [RCAL-644](https://jira.stsci.edu/browse/JP-644)
This PR addresses an issue found in I&T testing where the CRDS_CTX and CRDS_SVN are not being set properly after calibrations steps were run.
The issue was bad logic in checking whether the calibration code was running under a continuous-integration environment. Since such checks, within production code, are no longer, and should not be, needed, those checks have been removed.
**Checklist**
- ~updated relevant documentation~

RCAL-644 Remove checks on CI in production code

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml
.github/workflows/tests_devdeps.yml
JenkinsfileRT
JenkinsfileRT_dev
README.md
conftest.py
romancal/lib/tests/test_psf.py
tox.ini

Currently the `romancal` testing runs tests which require the `webbpsf`'s input data by default. This is undesirable because it requires users to have to set up this data in order for the test suite to complete successfully.
This PR adds the `--webbpsf` marker which enables these tests. This means that the `--webbpsf` flag must be passed to `pytest` in order to run the tests in question. This means that by default the `webbpsf` marked tests are not run. However,
this PR does add this marker to every CI job both on GitHub and Jenkins, so that the CI will always run the `webbpsf` tests. This means we will know prior to merging any changes if these tests are broken while also removing the burden of requiring outside users to not have to worry about `webbpsf`. 
**Checklist**

Skip webbpsf tests by default

---

CHANGES.rst
romancal/pipeline/exposure_pipeline.py
romancal/regtest/test_wfi_pipeline.py

Resolves [RCAL-697](https://jira.stsci.edu/browse/rcal-697)
Closes #951
**Checklist**
Jenkins is down the local regression test passes
pytest --bigdata /Users/ddavis/src/Roman/romancal/romancal/regtest/ --basetemp=/Users/ddavis/src/Roman/develop/test/tmp_tc -k test_level2_grism_processing 2>&1 |  tee test_pipeline_Oct27_2023_4.log
```
============================= test session starts ==============================
platform darwin -- Python 3.11.0, pytest-7.4.0, pluggy-1.2.0
plugins: remotedata-0.4.0, asdf-2.15.0, hypothesis-6.82.0, doctestplus-0.13.0, cov-4.1.0, filter-subpackage-0.1.2, mock-3.11.1, astropy-header-0.2.2, anyio-3.7.1, astropy-0.10.0, ci-watson-0.6.1, openfiles-0.5.0, env-0.8.2, …
```

rcal-697 Update exposure pipeline to add tweakreg step

---

.github/workflows/data.yml
.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml

This PR simplifies the data caching step by outsourcing the CRDS context retrieval to the reusable workflow from the CRDS repository. Also, renamed jobs to make them more explicit on what they do, and removed redundant `check/build-dist` check
**before**
**after**
**Checklist**

retrieve CRDS contexts in CI with a reusable workflow

---

pyproject.toml

This PR addresses the issue where test collection fails upon attempting to import in the new `static_preview` script:
https://github.com/spacetelescope/stcal/actions/runs/6772518526/job/18405280890#step:10:174
**Checklist**

don't run tests on `romancal/scripts`

---

romancal/scripts/static_preview.py

Closes #976
This PR protects the external dependencies by making them local to a function. This way they are not imported immediately.
**Checklist**

Protect imports in script better

---

CHANGES.rst
pyproject.toml
romancal/lib/psf.py
romancal/lib/tests/test_psf.py
romancal/source_detection/source_detection_step.py
romancal/source_detection/tests/test_source_detection_step.py

This PR improves astrometry in the Source Detection step by (optionally) making use of PSF fitting methods added in https://github.com/spacetelescope/romancal/pull/794.
The centroid accuracy of the PSF fitting methods depends on many factors, like the precision of the PSF model used in the fit (which may be traded off for longer runtimes), the flux of the source, the WFI filter, and to a lesser extent, the detector position, etc. The revised tests for source detection in this PR check the following criteria when using PSF fitting on bright sources in the F087 filter: 
* the median centroid residual is smaller than 3 milliarcseconds
* the maximum centroid residual is smaller than 11 milliarcseconds
* the recovered centroids and their errors are all <2-sigma consistent with the injected …

Source detection step option to fit model PSFs

---

JenkinsfileRT
JenkinsfileRT_dev

The url used to fetch webbpsf data for the jenkins runs:
```
https://stsci.box.com/shared/static/0ojjfg3cieqdpd18vl1bjnpe63r82dx8.gz
```
Appears to be down (regression test runs are failing to start and attempting to access the url locally results in a 'file upload in progress' page).
This PR updates the jenkins configuration files to use the webbpsf data on `/grp/` that is newly available from the webbpsf team as described in the docs:
https://webbpsf.readthedocs.io/en/latest/installation.html
Regression tests successfully run (these were started after the above url went down): https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/396/pipeline/220
**Checklist**

use webbpsf data from grp in jenkins runs

---

CHANGES.rst
romancal/lib/suffix.py
romancal/pipeline/exposure_pipeline.py
romancal/pipeline/highlevel_pipeline.py

Resolves [RCAL-707](https://jira.stsci.edu/browse/rcal-707)
Closes #
When running the pipeline with tweakreg set to "skip" tweakreg is returning a list and the pipeline is failing.
```
strun --disable-crds-steppar  --suffix='cal'  romancal.step.TweakRegStep test_tweakreg_asn.json
...
ERROR RUNNING STEP 'ExposurePipeline':
'list' object has no attribute '_models'
----------------------------------------------------------------------
> /Users/ddavis/src/Roman/romancal/romancal/pipeline/exposure_pipeline.py(196)process()
-> if hasattr(ModelContainer(result), "_models") and mc_result._models:
```
This converts the list to a container object before passing the object to tweakreg and results in
```
strun --disable-crds-steppar --suffix=cal romancal.step.TweakRegStep test_tweakreg_asn.json
... …
```

RCAL-707 Update elp to replace list as input to tweakreg

---

.github/workflows/data.yml

This PR addresses an issue where the cached WebbPSF data was not actually restored:
https://github.com/spacetelescope/romancal/actions/runs/6829635768/job/18623576605?pr=980#step:3:10
This was because the paths were different; GitHub Actions caches must have the same key AND path to match an `actions/cache` call
**Checklist**

fix issue where the path of the WebbPSF cache was not the same as the restore cache in the subsequent workflow

---

.github/workflows/tests_devdeps.yml

This PR addresses an issue where tests of development versions
1. had an incorrect caching setup
2. didn't test first-party (STScI) packages
**Checklist**

fix `tests_devdeps.yml` workflow

---

CHANGES.rst
romancal/lib/basic_utils.py
romancal/lib/tests/test_basic_utils.py
romancal/source_detection/source_detection_step.py
romancal/source_detection/tests/test_source_detection_step.py
romancal/tweakreg/tests/test_tweakreg.py
romancal/tweakreg/tweakreg_step.py

Source Detection produces a 2D ndarray of source IDs, centroids, and fluxes, to use as inputs in tweakreg. @schlafly and I discussed in https://github.com/spacetelescope/romancal/pull/841 that we could use a self-documenting and more scalable data structure instead if additional Source Detection results are useful for tweakreg or elsewhere. 
This PR swaps the unlabeled 2D ndarray for a structured array, and adds some helper functions for converting between ndarrays, structured arrays, and astropy tables.
Resolves [RCAL-709](https://jira.stsci.edu/browse/RCAL-709)
**Checklist**

Structured array source detection catalogs

---

CHANGES.rst
docs/conf.py
docs/roman/source_detection/arguments.rst
docs/roman/source_detection/description.rst
docs/roman/source_detection/index.rst
docs/roman/source_detection/psf.rst
romancal/lib/psf.py

This PR adds narrative docs for users and devs following the introduction of PSF fitting in Source Detection Step (#794, #841). This is a starting point, happy to iterate as reviewers see fit.
Resolves [RCAL-708](https://jira.stsci.edu/browse/RCAL-708)

Source detection+PSF docs updates

---

README.md

The [main header on the romancal README](https://github.com/spacetelescope/romancal#roman-calibration-pipeline) is in an unusual and unnecessary quote block:

Remove quote indent from main header in README

---

.github/workflows/data.yml

This PR addresses a small issue where the test cache does not contain the correct WebbPSF data hash:
This was because the job name defined in the workflow outputs was incorrect.
**Checklist**

minor fix for data hash in cache key

---

.github/pull_request_template.md
romancal/scripts/okify_regtests.py

Resolves [RCAL-718](https://jira.stsci.edu/browse/rcal-718)
Closes #1108
This PR updates the okify script to  the latest version of the jfrog cli
```
jfrog --version
jf version 2.51.1
```
The old version o longer supports the --build option used the in the okify script.
Update the script to conform to the new jfrog version syntax.
I've also update the pull request template so the default ticket in is RCAL-NNNN not the JWST project JP-NNNN
**Checklist**
- [ N/A ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

rcal-718 update okify script for the new jfrog cli

---

romancal/pipeline/exposure_pipeline.py

This PR marks the jump step as SKIPPED in the fully saturated case.

Mark jump step as skipped in fully-saturated case.

---

romancal/regtest/test_resample.py
romancal/tweakreg/tweakreg_step.py

This PR addresses updates the resample regression test to use file names from the newest set of files.  It also takes advantage of the asn_from_list module to jettison some home-made asn-making code.

Update resample test to use new files.

---

CHANGES.rst
docs/roman/references_general/dq_flags.inc
pyproject.toml
romancal/datamodels/container.py
romancal/lib/dqflags.py
romancal/outlier_detection/outlier_detection.py
romancal/outlier_detection/outlier_detection_step.py
romancal/resample/resample.py
romancal/stpipe/integration.py

Resolves [RCAL-501](https://jira.stsci.edu/browse/RCAL-501)
This PR addresses the implementation of the outlier detection step for Roman (replaces [PR#979](https://github.com/spacetelescope/romancal/pull/979)).
The link to the regression test results is [here](https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/464/).
**Checklist**

Implement outlier detection step.

---

romancal/outlier_detection/tests/test_outlier_detection.py

This PR disables the oulier detection unit tests, which aren't yet ready for primetime.

Disable outlier detection unit tests tests.

---

CHANGES.rst
romancal/pipeline/__init__.py
romancal/pipeline/highlevel_pipeline.py
romancal/stpipe/integration.py
romancal/stpipe/utilities.py

Resolves [RCAL-687](https://jira.stsci.edu/browse/rcal-687)
Closes https://github.com/spacetelescope/romancal/issues/924
This PR adds the level 3 pipeline code for high level processing. Testing the steps will need new data from INS.
Once we have the data the documentation and examples will be added to rtd.
The command to run the pipeline
strun --disable-crds-steppar roman_hlp r00005-a3001_image_001_short_asn.json
2023-11-14 14:34:26,342 - stpipe - WARNING - **WARNING**: LOCAL JWST PRD VERSION PRDOPSSOC-062 CANNOT BE CHECKED AGAINST ONLINE VERSION
2023-11-14 14:34:26,386 - stpipe.HighLevelPipeline - INFO - HighLevelPipeline instance created.
2023-11-14 14:34:26,387 - stpipe.HighLevelPipeline.skymatch - INFO - SkyMatchStep instance created.
2023-11-14 14:34:26,388 - …

rcal-687 Initial code for the high level pipeline

---

romancal/regtest/test_wfi_pipeline.py

Closes #
This PR adds a check for the preview file that needs to be generated for DMS278 (https://jira.stsci.edu/projects/RDM/issues/RDM-3153) and for imaging previews DMS281 (https://jira.stsci.edu/browse/RDM-3152)
**Checklist**

rcal-457 Add test for spectral preview files

---

romancal/dark_current/dark_current_step.py

This PR fixes a bug in dark subtraction where we try to subtract the full dark image, rather than the dark image truncated to the appropriate number of resultants.
Regression test here: https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/
There appear to be some unrelated failures in test_dq_init?

Truncate dark to the appropriate number of resultants.

---

CHANGES.rst
JenkinsfileRT
JenkinsfileRT_dev
pyproject.toml
romancal/stpipe/utilities.py

Closes #943
When `pytest --ddtrace` was run, like in the Jenkins CLI, the logs were getting polluted by all sorts of output from `ddtrace` This was due to two effects.
1. `pytest`'s `log_cli_level` was not set, so `pytest` was sending all the logs it did not internally generate (it will still capture and display logs as part of a failure/error message) to stdout. This has now been set to the recommended "info" level, so only logs more serious then "info" will get this treatment.
2. `ddtrace` was encountering an error as part of its injection of datadog into python every time a package was imported after this test: https://github.com/spacetelescope/romancal/blob/29cbeda93779f02122f275ac6edb9932191d0b38/romancal/lib/tests/test_suffix.py#L17-L26 was run. Indeed, I could reproduce this …

Fix the pollution of stdout and stderr by ddtrace

---

CHANGES.rst
romancal/lib/dms.py
romancal/regtest/test_ramp_fitting.py
romancal/regtest/test_wfi_pipeline.py

Resolves [RCAL-661](https://jira.stsci.edu/browse/rcal-661)
Resolves [RCAL-667](https://jira.stsci.edu/browse/rcal-667)
Resolves [RCAL-654](https://jira.stsci.edu/browse/rcal-654)
Resolves [RCAL-656](https://jira.stsci.edu/browse/rcal-656)
This PR implements the SOC test requirements for being able to calibrate uneven ramps in both the `RampFitStep` and `ExposurePipeline`
Note that RCAL_667 was mostly already done in the test `test_wfi_pipeline.py` module; the requirement message was simply updated. An additional check on `ImageModel` was added.
Note: Currently draft awaiting official test data.
**Checklist**
- ~updated relevant documentation~

RCAL-661/667/654/656 Implement next round of SOC verification tests for uneven ramps

---

CHANGES.rst
docs/roman/jump/arguments.rst
docs/roman/jump/even_ramp.rst
docs/roman/jump/index.rst
docs/roman/jump/uneven_ramp.rst
docs/roman/ramp_fitting/arguments.rst
docs/roman/ramp_fitting/description.rst

Resolves [RCAL-509](https://jira.stsci.edu/browse/RCAL-509)
Closes #760
This PR adds documentation for the uneven jump detection algorithm.
**Checklist**

RCAL-509: Update jump step docs

---

romancal/regtest/test_regtestdata.py

This PR fixes regression tests broken by spacetelescope/roman_datamodels#295. In those changes, data models now ensure their `meta.filename` (if they have one) is set in the written model to the name chosen for the file written. The broken tests wrote the same data model to two different file names and then tried to compare them. This PR simply makes it so that they placed in separate directories so they can have the same file name.
**Checklist**

Hotfix for regression tests broken by filename changes

---

CHANGES.rst
docs/conf.py
pyproject.toml

This PR removes `sphinx-asdf` as a requirement. It's primary purpose is to render asdf schemas in the docs. As romancal contains no schemas (those are in `rad`) the requirement for `sphinx-asdf` is not needed.
This fixes the current issue where the docs are rendered with a side/navigation menu that does not scroll when it overflows.
**Checklist**

drop sphinx-asdf requirement

---

CHANGES.rst
romancal/ramp_fitting/ramp_fit_step.py

Units test started failing when we made the WCS a required argument, because the unit tests relied on being able to construct ImageModels from default RampModels.  The latter don't have default WCSes, but the former require them, so the code to construct the one from the other needs to add a default WCS.
**Checklist**

Provide a default WCS for ramp fitting.

---

JenkinsfileRT
JenkinsfileRT_dev

Jenkins runs show errors in the logs for the `crds list` step:
from:  https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2Fromancal/detail/romancal/1092/pipeline
```
++ crds list --contexts roman_0051.pmap --mappings
++ grep pmap
CRDS - ERROR -  (FATAL) CRDS server connection and cache load FAILED.  Cannot continue.
See https://hst-crds.stsci.edu/docs/cmdline_bestrefs/ or https://jwst-crds.stsci.edu/docs/cmdline_bestrefs/
for more information on configuring CRDS,  particularly CRDS_PATH and CRDS_SERVER_URL. : [Errno 2] No such file or directory: '/grp/crds/roman/test/config/jwst/server_config'
+ echo 'CRDS_CONTEXT = '
CRDS_CONTEXT =
```
This appears to be due to crds defaulting to `jwst` when an observatory is not defined.
This PR updates the `CRDS_SERVER` environment …

switch jenkins runs to use roman-serverless for crds

---

.github/workflows/tests_devdeps.yml
requirements-dev-thirdparty.txt
tox.ini

Add python 3.12 devdeps testing.
**Checklist**

Add python 3.12 devdeps testing

---

CHANGES.rst
romancal/regtest/regtestdata.py

Resolves [RCAL-724](https://jira.stsci.edu/browse/RCAL-724)
Closes #1027
Currently the `compare_asdf` diff reports only return the deep diff results which indicate any differences between two asdf files. Why this is very useful, it does not tell the entire story; namely, it does not indicate what the diff was of. Issue #1027 indicates that it would be useful to know both the files being compared and the model names for the `roman_datamodels` included within those files (if applicable).
This PR adds a small header string to the start of the diff report that indicates the files input into `compare_asdf` and attempts to determine the `roman_datamodels` model described by the file (returning `Not a model` if the file does not describe a `roman_datamodel`), returning both for the "result" and …

RCAL-724: Add additional information to `compare_asdf` diff reports.

---

CHANGES.rst
romancal/refpix/refpix.py
romancal/refpix/refpix_step.py
romancal/refpix/tests/reference_utils.py
romancal/refpix/tests/test_data.py
romancal/refpix/tests/test_refpix.py

The original Goddard code effectively had this turned off, so in order to replicate those results this was turned off in `romancal` on purpose too even though was part of the Goddard code. This was reported to Goddard as a potential bug, and was confirmed to be a bug in the reference implementation by Goddard.
This PR enables the apodized FFT interpolation by default
**Checklist**

Turn on the apodized FFT interpolation

---

requirements-sdp.txt

This PR adds `sdp` to the instructions for populating `requirements-sdp.txt`, so that the `sdp` requirements are included in the final released requirement file `reqs_stable-deps.txt` on Artifactory
**Checklist**
- [ N/A ] ~added entry in `CHANGES.rst` under the corresponding subsection~
- [ N/A ] ~updated relevant tests~
- [ N/A ] ~ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)~

update `requirements-sdp.txt` instructions to include the `sdp` extra

---

romancal/dq_init/tests/test_dq_init.py
romancal/flatfield/tests/test_flatfield.py

In testing `romancal` using spacetelescope/rad#369, the only failures in both the unit and regression tests were due to a few incorrectly defined `dtypes` used within the tests themselves. These were all minor bugs that did not effect anything major.
**Checklist**

Fix a few incorrect dtypes used in tests

---

docs/conftest.py
pyproject.toml
romancal/assign_wcs/tests/test_wcs.py
romancal/associations/tests/test_asn_from_list.py
romancal/associations/tests/test_pool.py
romancal/dark_current/tests/test_dark.py
romancal/jump/tests/test_jump_step.py

[`pytest` recommends creating temporary directories with the `tmp_path` fixture instead of the legacy `tmpdir`](https://docs.pytest.org/en/latest/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures). To check for use of the legacy method one can run with
```
pytest -p no:legacypath
```
This PR used that command to discover all uses of `tmpdir` and correct them. It does not add this as a permanent check because the `pytest_asdf` plugin that is built into the `asdf` package relies on this legacy system. This was fixed by asdf_format/asdf#1759, but has not been released yet.
**Checklist**

Find and fix all the tmpdir usages

---

.github/workflows/roman_ci.yml
pyproject.toml
romancal/conftest.py
romancal/regtest/conftest.py
tox.ini

Incompatibility between ddtrace (and ci_watson) and the `-p no:legacypath` option for pytest means that the `-p no:legacypath` option cannot be "globally" enabled.
This PR instead enables the option as a tox factor and uses the factor for a single pytest suite run `py310-webbpsf-nolegacypath`. This will allow romancal to keep the current asdf lower pin, not wait until ddtrace and ci_watson are updated and still reap most of the benefits of the `-p no:legacypath` option as all tests run during the `py310-webbpsf-nolegacypath` run will be checked for legacy path usage.
Regtests were run with no errors `-p no:legacypath` (and ddtrace disabled):
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/616/pipeline/ …

remove `tmpdir_factory` usage, enable no:legacypath as a tox factor

---

CHANGES.rst
romancal/dq_init/dq_init_step.py

`dqinit` adds data views to the resulting datamodel which when saved triggers asdf to save the base array resulting in large file sizes. Similar to https://github.com/spacetelescope/romancal/pull/1098 this PR adds copies of those arrays to the output datamodel to avoid larger-than-needed file sizes.
Without this PR running the `elp` benchmarks (each step in `elp) with a [330Mb input file](https://bytesalad.stsci.edu/ui/repos/tree/General/benchmark-data/roman/exposure_pipeline/r0000101001001001001_01101_0001_WFI01_uncal.asdf) produces files with sizes as follows:
| step | output file size |
| ---- | ---------------|
| dqinit | 1.5 G |
| saturation | 1.5 G |
| refpix | 2.2 G |
| linearity | 2.2 G |
| darkcurrent | 2.2 G |
| rampfit | 332 M |
| assignwcs | 332 M |
| flatfield | 395 M |
| …

copy reference pixels during dqinit

---

romancal/regtest/test_wfi_dq_init.py

Fix DMS requirement number

---

CHANGES.rst
docs/roman/ramp_fitting/description.rst
romancal/ramp_fitting/ramp_fit_step.py
romancal/ramp_fitting/tests/test_ramp_fit_cas22.py

Presently the ramp fitting step operates on dark-subtracted ramps, but assumes that the Poisson noise in those ramps can be well estimated by the square root of the rate.  The dark current contribution to the rate should be part of that Poisson noise, but is omitted because the step operates on dark-subtracted ramps.
This PR adds the dark current portion of the dark reference file (dark_slope) back into the ramp, performs the ramp fitting, and then removes the contribution from the slopes.  This is related to
https://innerspace.stsci.edu/display/RI/Ramp+Fitting+-+v1
.  It has the slight benefit of being more correct (we're choosing weights better), but being more convoluted (we're adding and subtracting dark current.
We'll also use more memory than previously---the darks are rather big, …

Use dark slope in ramp fitting

---

romancal/regtest/conftest.py

https://github.com/spacetelescope/romancal/pull/1117 missed that the `_jail` and `jail` fixtures were indirectly used in the regtest teardown postmortem. The impact can be seen in a recent regtest run of romancal main (that includes unrelated failures):
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/644/
where `test_rampfit_step[spec_full]` fails and then fails to generate a postmortem with the error:
```
ailed on teardown with "KeyError: 'jail'"
```
This PR fixes the indirect usage.
Regtests with this PR show the unrelated failures:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/646/tests
with the `test_rampfit_step[spec_full]` failure now showing the more helpful:
``` …
```

fix regtest teardown for fixture updates

---

CHANGES.rst
romancal/regtest/test_ramp_fitting.py
romancal/regtest/test_wfi_16resultants.py
romancal/regtest/test_wfi_dq_init.py
romancal/regtest/test_wfi_flat_field.py
romancal/regtest/test_wfi_photom.py
romancal/regtest/test_wfi_saturation.py
romancal/scripts/make_regtestdata.sh
romancal/tweakreg/astrometric_utils.py
romancal/tweakreg/tests/test_astrometric_utils.py
romancal/tweakreg/tests/test_tweakreg.py

This PR consolidates the regression tests to use fewer files and adds a script to create all of the regression test files from a directory of input files.
Changes to the regression tests:
- Point ramp fitting tests to WFI01 and darkcurrent subtracted files.  We had these pointing to weird files to deal with a caching issue and a shape issue in the run-up to B12; we don't need to continue doing that.
- Point test_wfi_dq_init, test_wfi_flat_field, test_wfi_saturation tests to the one fiducial spectroscopic regression test file; these formerly used a second file but I'm not sure what the motivation for that originally was.
- Rename the munged L1 file with a different time to be clear that this is a file we are making with a weird time rather than a file from RTB.
- Move some test_wfi_photom …

Consolidate regression tests into fewer files.

---

romancal/regtest/regtestdata.py
romancal/regtest/test_regtestdata.py

While looking into unrelated regtest failures I noticed the `n_diffs` calculation in `compare_asdf` counts the number of matching not differing values. This PR adds a test for the calculation and fixes the issue.
**Checklist**

fix n_diffs in compare_asdf

---

CHANGES.rst
romancal/outlier_detection/outlier_detection.py
romancal/outlier_detection/tests/test_outlier_detection.py

Resolves [RCAL-725](https://jira.stsci.edu/browse/RCAL-725)
This PR fixes a bug with the outlier detection step in which the algorithm was still detecting outliers even if the input models were identical. Additionally, the median image was not being properly created, which was being caused by wrongly setting the `single` parameter in the call to resample.
A unit test for identical input datamodels was added.
**Regression tests**
No errors/failures were reported:
- https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/655/
**Checklist**

RCAL-725: fix outlier detection step issues.

---

CHANGES.rst
romancal/dq_init/dq_init_step.py
romancal/dq_init/tests/test_dq_init.py

Fixes #1150
During transfer of attributes from the input model during `DQInitStep`, the presence of attribute not defined in `RampModel` will lead to an error (see above issue).
This PR checks if the attribute exists in `RampModel` and if not creates it.
Regtests running at: https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/682/
**Checklist**

allow DQInitStep to pass through non-rampmodel keys

---

CHANGES.rst
romancal/datamodels/container.py
romancal/datamodels/tests/test_datamodels.py

Resolves [RCAL-620](https://jira.stsci.edu/browse/RCAL-620)
This PR implements two magic methods (`.__enter__()` and `.__exit__()`) that allows `ModelContainer` to work properly with a context manager.
Two unit tests have been added to test the new implementation.
**Regression test**
No errors/failures reported:
~https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/661/~
~https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/683/~
~https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/690/~
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/691/
**Checklist**

RCAL-620: allow ModelContainer to work with context manager.

---

romancal/regtest/test_hlp_pipeline.py
romancal/scripts/make_regtestdata.sh

This PR updates the HLP regtest to use existing L1/L2 files rather than add new ones.  This reduces the number of files we need to track.
It also adds the corresponding L3 image creation to the regtest file creation script.
**Checklist**

Update HLP regtest to use existing L1/L2 files

---

CHANGES.rst
romancal/flux/flux_step.py

Resolves [RCAL-800](https://jira.stsci.edu/browse/RCAL-800)
Related PRs:
- [roman_datamodel#332](https://github.com/spacetelescope/roman_datamodels/pull/332)
- [rad#395](https://github.com/spacetelescope/rad/pull/395)
This PR sets the step completion status for each input model to FluxStep.
**Checklist**

RCAL-800: Set flux step status for each input

---

CHANGES.rst
romancal/resample/gwcs_drizzle.py
romancal/resample/tests/test_gwcs_drizzle.py
romancal/resample/tests/test_resample.py
romancal/resample/tests/test_resample_step.py

Resolves [RCAL-795](https://jira.stsci.edu/browse/RCAL-795)
This PR fixes a bug in the resample step in which the output weight and context arrays were being reset to zero every time a new image was added to the drizzle object.
**Regression tests**
No issues due to the changes in this PR.
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/706/
**Checklist**

RCAL-795: fix incorrect weight maps returned by resampling

---

README.md

The `stsci_logo.png` does not exist in `docs/_static`.  It looks like this line was copied from the`jwst` readme, but the logo was not.
**Checklist**

Remove link to non-existent STScI logo

---

CHANGES.rst
romancal/regtest/conftest.py
romancal/stpipe/core.py
romancal/stpipe/tests/test_core.py

This PR updates `meta.calibration_software_version` in models returned from step runs. This is set to the current romancal version (instead of using the default [9.9.0](https://github.com/spacetelescope/roman_datamodels/blob/bb788f4c39d8d62e78f62b239d0d769c16dbcf85/src/roman_datamodels/maker_utils/_basic_meta.py#L16) which appears in many if not all files).
`meta.calibration_software_version` is also added to the "ignores" used for compare_asdf for regression tests.
Regression tests show 2 unrelated failures (which are also occurring on main):
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/713/tests
The unrelated failure is helpful here as the failing test produced …

update calibration_software_version when a step is run

---

CHANGES.rst
romancal/regtest/test_hlp_pipeline.py

Resolves [RCAL-818](https://jira.stsci.edu/browse/RCAL-818)
Closes #
This PR adds a check for the creation of preview images to the hlp regtest. Here is the log entries for that portion,
```
2024-04-26 08:29:29,672 - stpipe.HighLevelPipeline - INFO - Status of the step:             thumbnail image    Pass
INFO     stpipe.HighLevelPipeline:log_config.py:142 Status of the step:             thumbnail image    Pass
2024-04-26 08:29:29,673 - stpipe.HighLevelPipeline - INFO - Status of the step:             preview image    Pass
INFO     stpipe.HighLevelPipeline:log_config.py:142 Status of the step:             preview image    Pass
```
**Checklist**
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/718/
This only shows the two …

rcal-818 Add preview images tp hlp regtest

---

docs/roman/flux/main.rst

The `flux` step appears to assume the input units are DN/s, not e/s.
**Checklist**

Fix unit typo in docs

---

CHANGES.rst
romancal/resample/resample.py
romancal/resample/tests/test_resample.py

Resolves [RCAL-816](https://jira.stsci.edu/browse/RCAL-816)
This PR adds a function to populate the L3 mosaic output from resample with basic info about times, observation setup, and others. A unit test was also implemented to test the new function.
**Regression tests**
~https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/711/~
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/712/
**Checklist**

RCAL-816: add function to populate L3 mosaic meta.basic.

---

CHANGES.rst
romancal/assign_wcs/utils.py
romancal/resample/resample.py

This PR addresses an issue found during HLP development. If a rotation matrix needs to be calculated, in order to populate the wcsinfo block, the resultant form was not compatible with the schema. This PR fixes that formatting.
**Checklist**

make rotation matrix 2d for schema validation

---

CHANGES.rst
docs/roman/package_index.rst
docs/roman/pipeline_steps.rst
docs/roman/source_catalog/arguments.rst
docs/roman/source_catalog/index.rst
docs/roman/source_catalog/main.rst
romancal/lib/suffix.py
romancal/regtest/test_catalog.py
romancal/scripts/make_regtestdata.sh
romancal/source_catalog/__init__.py
romancal/source_catalog/_wcs_helpers.py
romancal/source_catalog/background.py
romancal/source_catalog/detection.py
romancal/source_catalog/reference_data.py
romancal/source_catalog/source_catalog.py
romancal/source_catalog/source_catalog_step.py
romancal/source_catalog/tests/test_source_catalog.py
romancal/step.py
romancal/stpipe/integration.py

Resolves [RCAL-764](https://jira.stsci.edu/browse/RCAL-764)
Closes #1083
This PR ports the Source Catalog Step from `jwst`. We're currently discussing what level of support we'll implement in this PR for AB/Vega mags.
* https://github.com/spacetelescope/rad/pull/374
* https://github.com/spacetelescope/roman_datamodels/pull/317
**Checklist**

Add Source Catalog Step

---

CHANGES.rst
romancal/conftest.py
romancal/skymatch/skymatch_step.py
romancal/skymatch/tests/test_skymatch.py

Resolves [RCAL-801](https://jira.stsci.edu/browse/RCAL-801)
This PR ensures that `SkyMatchStep` always returns a `ModelContainer` with the updated datamodel.
I believe `SkyMatchStep` is due some refactoring (specifically regarding the intended use of memory management, as seen in JWST's `SkyMatchStep`), but I think that it should be done separately from the current PR.
**Regression Tests**
- https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/721/
**Checklist**

RCAL-801: update skymatch to return updated models if the input is an asn

---

CHANGES.rst
romancal/regtest/conftest.py
romancal/resample/resample.py
romancal/stpipe/core.py

This PR leads HLP products to have their "cal_logs" attribute filled out.
Previously these were not being populated because stpipe.core was explicitly checking that the output datamodel was an ImageModel.  This PR changes that to check if it's either an ImageModel or a MosaicModel.  It also clears the CalLogs when making a new output model to avoid some initial filler values.
Finally, a big portion of the HLP is processing the input L2s; flux calibration, sky matching, outlier detection.  Those logs go into the L2 products which we do not save.  This adds a new individual_image_cal_logs extension parallel to cal_logs that houses the individual L2 log messages.  We probably want that?
**Checklist**

Make sure logs get included in L3 products.

---

CHANGES.rst
romancal/datamodels/container.py
romancal/resample/resample.py

This PR puts the real file names in meta.resample.members rather than the individual file name meta.filename attributes.  This is intended to address https://github.com/spacetelescope/romancal/issues/1154 , but is rather awkward.
The challenge is that the ModelContainer passed to resample doesn't know about the original file names.  This PR digs around the private contents of the datamodel to grab the input file name, and if that fails, falls back to img.meta.filename.  But relying on img._asdf._fname is clearly asking for trouble.
The alternative would be to teach ModelContainer about the input file names if it's read from an association.  That would add a new filenames member to ModelContainer that defaults to None, and sets the new filenames to be equal to _models if everything is a …

Put real file names in meta.resample.meta.

---

romancal/regtest/test_hlp_pipeline.py

This PR addresses problems brought by `sonarqube`: https://plsonarqube.stsci.edu/project/issues?resolved=false&inNewCodePeriod=true&types=BUG&id=romancal&open=AY8c5NNYlU1kwdd-S5_H
**Checklist**

fix incorrect boolean comparison within `isfile()`

---

CHANGES.rst
romancal/pipeline/highlevel_pipeline.py
romancal/resample/resample.py

Resolves [RCAL-803](https://jira.stsci.edu/browse/RCAL-803)
Closes #1162
This PR adds the ability to use an association to resample the members to the output product based on a skycell definition.
**Checklist**
The regression tests at https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/732/
are passing.

Rcal 803 Initial resampling to skycell in the hlp

---

CHANGES.rst
romancal/patch_match/patch_plot.py

Closes #1203
This PR addresses adds a plotting utility that shows the spatial relationship of an image to the patches that have been deemed to be those overlapped by the image, as well as the candidate patches tested for an overlap. The purpose is mainly for diagnostic use.

adding plotting utility

---

romancal/regtest/regtestdata.py

This PR ignores an additional Table metadata version field in compare_asdf.

Also ignore version information in Table schema meta.

---

romancal/outlier_detection/tests/test_outlier_detection.py

The `clean_up_after_test` fixture usage in the outlier detection tests deletes all asdf files in the working directory (even if they were not created by the tests). The tests that use this fixture also do not change the working directory. This can (and did result) result in deletion of user files (unrelated to the unit or regression tests) with no warnings.
This resulted in deletion of a large number of files (which were not generated by the tests and are now lost) when I ran the outlier detection tests.
This PR removes the fixture. It could later be replaced with a more specific cleanup.
Fixes: https://github.com/spacetelescope/romancal/issues/1244
**Checklist**
Regression tests run with no errors:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-R …

remove clean_up_after_test

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml

turns out, we have a token but just weren't using it in the CI
**Checklist**

add `codecov_token` secret to CI workflow

---

CHANGES.rst
docs/roman/pipeline/mosaic_pipeline.rst
romancal/pipeline/mosaic_pipeline.py
romancal/regtest/test_mos_pipeline.py

Resolves [RCAL-850](https://jira.stsci.edu/browse/RCAL-850)
Closes #1256 
This PR adds the source catalog step to run on the resampled image at the end of the mosaic pipeline to create the
_cat.asdf 
_segm.asdf
files.
**Checklist**
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/813/

rcal-850 Addition of catalog step to mosaic pipeline

---

CHANGES.rst
docs/roman/pipeline/exposure_pipeline.rst
romancal/pipeline/exposure_pipeline.py

Resolves [RCAL-854](https://jira.stsci.edu/browse/RCAL-854)
Closes #1263
This PR fixes the error that the tweakreg step is listed as skipped when it is run. This PR also refactors the
exposure level pipeline to take advantage of the model container and associations. 
**Checklist**
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/828/
The regression test truth data will need updating to fix the tests ( cal_step SKIPPED --> COMPLETE)

Rcal 854 Tweakreg step listed as skipped when run & refactor exposure pipeline

---

romancal/resample/resample_step.py

configobj use from stpipe is deprecated. This is causing [warnings in test runs](https://github.com/spacetelescope/romancal/actions/runs/9409925545/job/25920739724#step:10:262):
```
/home/runner/work/romancal/romancal/.tox/py311-ddtrace-webbpsf/lib/python3.11/site-packages/ddtrace/internal/module.py:220: DeprecationWarning: stpipe.extern.configobj is deprecated in favor of astropy.extern.configobj, please use that instead.
```
This PR uses configobj from astropy similar to what is done in [jwst](https://github.com/spacetelescope/jwst/blob/e1b66cc4c8c8d2cafd2be4828de7de67184f56a6/jwst/resample/resample_step.py#L8).
With this PR the warning is no longer seen in the test runs:
https://github.com/spacetelescope/romancal/actions/runs/9418970328/job/25947683547?pr=1267#step:10:260
**Checklist**

replace deprecated stpipe configobj with astropy

---

JenkinsfileRT
JenkinsfileRT_dev

* The version (24.x) installed by miniforge is sufficient. 22.x is too old.
Ref: https://github.com/spacetelescope/jenkins_shared_ci_utils/pull/94
Ref: https://github.com/spacetelescope/jwst/pull/8585

Do not set conda version in Jenkinsfile(s)

---

CHANGES.rst
romancal/scripts/okify_regtests.py

Resolves [RCAL-859](https://jira.stsci.edu/browse/RCAL-859)
Closes #1281 
This PR updates the okify script to use the GA directories in artifactory.
**Checklist**
- [N/a] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

rcal-859 Update okify script to use GA directories on artifactory

---

pyproject.toml

This PR removes the exact pin for webbpsf. The pinned version is not numpy 2.0 compatible and is one of the limitations preventing romancal from using numpy 2.0:
https://github.com/spacetelescope/romancal/issues/1280
I pinged @bmorris3 to see if he recalls the reason for the exact pin in: https://github.com/spacetelescope/romancal/pull/841
This PR will test if removing the pin causes test failures.
Regression tests run with no errors at:
https://github.com/spacetelescope/RegressionTests/actions/runs/9652327358
Fixes https://github.com/spacetelescope/romancal/issues/1280
**Checklist**

unpin webbpsf

---

CHANGES.rst
romancal/pipeline/mosaic_pipeline.py

This PR fixes some issues in the of the skycell WCS.
Formerly, the code used the center pixel of the WCS to mark the edge of the bounding box.  That meant that the bounding box only covered a quarter of the image, leading to issues.
The "shift" used to move from the projection center was also using the edge of the bounding box.  We now use the projection center in x/y coordinates.
This is intended to address an issue that @snbianco raised.  I've placed a new example L3 image at
/grp/roman/eschlafly/misc/r0099101001001001001_F158_visit_r274dp63x31y81_i2d.asdf
that should have this issue fixed, but please check!

Fix issue in constructing skycell WCS.

---

pyproject.toml

This PR allows pytest to show captured log messages for failed tests by removing `--show-capture=no` from the pytest options.
Regtests passed with no errors: https://github.com/spacetelescope/RegressionTests/actions/runs/9959656242
**Checklist**

show logs on failed tests

---

pyproject.toml

The `pyproject.toml` file contains configuration for the pytest asdf plugin (for testing schemas):
https://github.com/spacetelescope/romancal/blob/459e8e345bbb1ba6bfd76d0d8a90f2058089791e/pyproject.toml#L135-L137
However there is no `romancal/datamodels/schemas` (the schemas exist and are tested in rad).
This PR removes the unnecessary configuration.
With this PR pytest finds 854 test items:
https://github.com/spacetelescope/romancal/actions/runs/9958232059/job/27512161042?pr=1305#step:10:154
the same number is found on main:
https://github.com/spacetelescope/romancal/actions/runs/9893953303/job/27330394884#step:10:154
verifying that no schemas are found for testing and that the configuration removed in this PR was doing nothing (but was adding an implicit dependency on the asdf pytest …

remove pytest asdf plugin configuration for non-existant schemas

---

CHANGES.rst
romancal/tweakreg/tests/test_tweakreg.py
romancal/tweakreg/tweakreg_step.py

Closes #1306 
This PR eliminates the global variable `ALIGN_TO_ABS_REFCAT` from `TweakRegStep` and the two unit tests that used it. Since `TweakRegStep` is always used for absolute astrometry, there is no need to have that global variable with fixed value.
**Regression Tests**
All tests are passing:
- https://github.com/spacetelescope/RegressionTests/actions/runs/9983530132
**Checklist**

Remove unnecessary global variable and unit tests.

---

CHANGES.rst
docs/roman/datamodels/datamodels_asdf.rst
pyproject.toml
romancal/linearity/linearity_step.py
romancal/regtest/regtestdata.py

follow-on to https://github.com/asdf-format/asdf/pull/1797
**Checklist**

replace usages of ``copy_arrays`` with ``memmap``

---

romancal/outlier_detection/outlier_detection.py

As noted https://github.com/spacetelescope/romancal/commit/c49de361201c37ee2149e9e537645137bd6df655#r144502886
https://github.com/spacetelescope/romancal/pull/1241 included unreachable code.
This is being flagged by sonarqube and preventing regression tests.
This PR deletes the unreachable code. I can also confirm that I intended to delete the code for #1241 but missed it in the swatch of changes.
Regression tests running:
https://github.com/spacetelescope/RegressionTests/actions/runs/10043812086
passed quality gate, tests running.
Fixes: https://github.com/spacetelescope/romancal/issues/1321
**Checklist**

delete unreachable code

---

CHANGES.rst
pyproject.toml

Closes #
This PR pins stcal so that the new AIP changes will not break new installs of romancal. Once these AIP changes are implemented in romancal the upper pin can be removed. 
**Checklist**
- [n/a] updated relevant tests
- [n/a] updated relevant documentation
The passing tests are at 
https://github.com/spacetelescope/RegressionTests/actions/runs/10058317955

Pin stcal for development

---

pyproject.toml
romancal/stpipe/core.py

Requires https://github.com/spacetelescope/stpipe/pull/171
Regression tests all pass:
https://github.com/spacetelescope/RegressionTests/actions/runs/10063338609/job/27821316132
See the above linked stpipe PR for more details.
During step runs, stpipe records log messages to `Step.log_records`. This can result in steady accumulation of memory as these are `LogRecord` instances that retain references to their arguments. That means that a log message like the following:
```python
log.info("Calibration array: %s", big_array)
```
Will prevent `big_array` from being garbage collected until the `Step` in which the log message occurred can be collected. One such problematic log message exists in stpipe (see the linked PR) which logs the input datamodel for a step.
Within the context of romancal, …

provide formatter to log_records

---

pyproject.toml

See https://github.com/spacetelescope/stpipe/pull/174 for details about the stpipe 0.6.1 release.
The tldr is that it contains breaking changes to fix a memory leak. The changes are compatible with romancal main following https://github.com/spacetelescope/romancal/pull/1327 but as #1327 will not be backported to the released 0.15.x branch this PR adds an upper pin to allow the released versions of romancal to not use stpipe 0.6.1.
**Checklist**

pin stpipe < 0.6.1 on 0.15.x release branch

---

.github/labeler.yml

follow-on to #1231 and #1332 
**Checklist**

update labeler to v5

---

romancal/lib/psf.py
romancal/lib/tests/test_psf.py
romancal/source_catalog/source_catalog.py
romancal/source_detection/source_detection_step.py

Regression tests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/10165236470
This PR removes the creation of a `fits` file during `create_gridded_psf_model`.
Closes #1328
Local testing running `roman_elp` (which previously produced a `tmp_sca01.fits`) shows that the stray `fits` file is no longer produced with this PR.
**Checklist**

remove creation of stray fits file

---

pyproject.toml

https://github.com/spacetelescope/roman_datamodels/pull/358 increased the minimum required asdf version for roman_datamodels to 3.1.0.
This PR updates the asdf requirement in romancal to match (to allow the oldest deps job to run).
I marked this as `no-changelog-entry-needed` but please let me know if an entry is preferred.
Given the regtests ran with https://github.com/spacetelescope/roman_datamodels/pull/358 I did not start a run with this PR. Please let me know if I should.
**Checklist**

increase asdf minimum required version

---

CHANGES.rst
romancal/assign_wcs/assign_wcs_step.py
romancal/dark_current/dark_current_step.py
romancal/dq_init/dq_init_step.py
romancal/flatfield/flat_field_step.py
romancal/jump/jump_step.py
romancal/linearity/linearity_step.py
romancal/photom/photom_step.py
romancal/refpix/refpix_step.py
romancal/regtest/regtestdata.py
romancal/regtest/test_mos_pipeline.py
romancal/regtest/test_wfi_16resultants.py
romancal/regtest/test_wfi_pipeline.py
romancal/saturation/saturation_step.py
romancal/source_catalog/source_catalog_step.py
romancal/source_detection/source_detection_step.py

This PR removes (almost) all uses of `lazy_load=False` (the ones in `make_regtestdata.sh` were left unchanged).
In several places this required changes to how steps handle input. The closed ticket (#1341) more details but briefly:
```python
def process(self, init):
with rdm.open(init) as model:
return model
```
The above typical step process function results in returning a closed model for any step when run with a filename as an input due to:
- rdm.open opening the file
- the existing of the `with` statement closing the file
Any portion of `model` not modified or accessed during the `process` run can result in an error in a later step. For example if the step does not access `model.err`, the `err` array will not be loaded before the input file is closed. Any later step that attempts to …

Remove uses of `lazy_load=False`, update step input handling

---

CHANGES.rst
romancal/regtest/test_mos_pipeline.py

Resolves [RCAL-827](https://jira.stsci.edu/browse/RCAL-827)
Closes #1218 
This PR adds a regression test for resampling data to a skycell (DMS 373). Currently it uses the SCSB skycell definitions but will be changed to the RTB definitions once available. 
**Checklist**
The passing regression tests are at
https://github.com/spacetelescope/RegressionTests/actions/runs/10219749253
and
https://github.com/spacetelescope/RegressionTests/actions/runs/10220085169
The only issue is that we will need to have 
PATCH_TABLE_PATH=/grp/roman/scsb/tesselation/patches.asdf
added to the romancal.yml file for GitHub actions (https://github.com/spacetelescope/RegressionTests/pull/112) before merging.

rcal-827 Add reg test for DMS373

---

romancal/regtest/regtestdata.py
romancal/regtest/test_mos_pipeline.py
romancal/regtest/test_resample.py

Fixes https://github.com/spacetelescope/romancal/issues/1318
This PR uncomments `get_asn` and uses it in the 2 regtests I found that pull associations from artifactory.
This allows the regtests to be simplified by not requiring them to:
- download files in an association in addition to the association
- `get_asn` automatically sets the `rtdata.input` attribute so the test does not need to set this
Regression tests running:
https://github.com/spacetelescope/RegressionTests/actions/runs/10267768330
**Checklist**

uncomment and use get_asn

---

romancal/jump/tests/test_jump_step.py

Make CRs bigger than the threshold used for the new pars files.
Fixes the unit test failures seen in:
https://github.com/spacetelescope/romancal/pull/1355
due to the new pars file:
https://roman-crds.stsci.edu/browse/roman_wfi_pars-jumpstep_0001.asdf
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/10308257135
show only expected differences due to the new crds context:
```
E         {'values_changed': {"root['roman']['meta']['ref_file']['crds']['context_used']": {'new_value': 'roman_0063.pmap',
E                                                                                           'old_value': 'roman_0061.pmap'}}}
```
**Checklist**

make crs bigger for new pars file for jump unit tests

---

CHANGES.rst
romancal/resample/resample.py

roman_datamodels defaults the context plane of the mosaic model to start with 2 planes:
https://github.com/spacetelescope/roman_datamodels/blob/5e996c37648bac7fa0ac3c4d5e0ce5b8ddaeb69a/src/roman_datamodels/maker_utils/_datamodels.py#L155
This is causing an extra context plane. This PR fixes the issue by setting n_images to 1.
Closes https://github.com/spacetelescope/romancal/issues/1264
Regression tests show 2 expected failures (which shows the issue is fixed): https://github.com/spacetelescope/RegressionTests/actions/runs/10303608077
**Checklist**

fix number of context planes

---

CHANGES.rst
romancal/skymatch/skymatch_step.py

Make sure that we send sensible metadata even when the L2 images don't overlap one another.  The existing code populates Nones here, which don't fit into the individual_image_metadata tables with the other numbers.
Regression tests are passing: https://github.com/spacetelescope/romancal/pull/1355

Populate sky metadata with zero if matching is not possible.

---

CHANGES.rst
README.md
pyproject.toml

release metadata for `0.16.1` + update `stpipe` to use `ModelLibrary` + `stcal` to use outlier detection functions

---

CHANGES.rst
romancal/pipeline/exposure_pipeline.py
romancal/regtest/test_wfi_pipeline.py

Resolves [RCAL-898](https://jira.stsci.edu/browse/RCAL-898)
Closes #1379 
This PR addresses an issue in OPS where files generated from the ELP do not have the expected suffix.
With this change passing `--sufix=` to the `strun` command generates output with the specified suffix. If no suffix is passed, the default suffix is `cal`. 
**Checklist**

Add a default suffix to ELP

---

CHANGES.rst
romancal/patch_match/patch_match.py
romancal/pipeline/mosaic_pipeline.py

This PR modifies the mosaic pipeline and patch match submodule to only load the patch table when required (instead of at import).
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/10404395165
Closes #1366
**Checklist**

only load patch table when needed

---

CHANGES.rst
romancal/outlier_detection/outlier_detection_step.py
romancal/pipeline/mosaic_pipeline.py
romancal/resample/resample_step.py
romancal/source_catalog/source_catalog_step.py
romancal/source_catalog/tests/test_source_catalog.py

Closes #1389 
We were previously populating segmentation image metadata with filler values that were not related to the input L2 or L3 image.  This PR adds code that copies the metadata from the catalogs into the segmentation images.
This now also fixes some file naming issues; the mosaic pipeline was saving the catalogs, as well as the step saving the catalogs, leading to two copies of the catalogs with different file names.  Now only the step saves the catalogs.  I have also changed some of the logic around the construction of the file names.
Regtests running here: https://github.com/spacetelescope/RegressionTests/actions/runs/10600468693/job/29383387213
**Checklist**

Populate segmentation model metadata for exposures and mosaics.

---

CHANGES.rst
romancal/pipeline/mosaic_pipeline.py

Resolves [RCAL-906](https://jira.stsci.edu/browse/RCAL-906)
Closes #1390
This PR allows the asn product name to be the output product name
**Checklist**
The passing regression tests are at: 
https://github.com/spacetelescope/RegressionTests/actions/runs/10635674348

rcal-906 Allow asn product name to be the output product name

---

.github/pull_request_template.md
.github/workflows/changelog.yml
.readthedocs.yaml
CHANGES.rst
changes/1375.docs.rst
changes/1394.mosaic_pipeline.rst
docs/index.rst
docs/roman/changes.rst
docs/rtd_environment.yaml
pyproject.toml

using `towncrier` to handle changelog entries will
- drastically reduce (or even eliminate) branch conflicts in `CHANGES.rst` we currently experience with PRs
- keep the sections in `CHANGES.rst` consistent and eliminate duplicate sections
- allow automatic links to be generated in the changelog entries
[<img width="1152" alt="image" src="https://github.com/user-attachments/assets/a6775dd3-7656-43da-9293-09e2b93090c7">](https://roman-pipeline--1375.org.readthedocs.build/en/1375/roman/changes.html)
`towncrier` expects "news fragment" files (text files in the `changes/` directory with filenames in the format `<PR#>.<changetype>.rst`, i.e. for this PR it would be `changes/1375.docs.rst`). See docs at https://towncrier.readthedocs.io/en/latest/tutorial.html#creating-news-fragments
when ready …

use `towncrier` to handle changelog entries

---

pyproject.toml

This PR removes the upper pin for pytest and updates the lower pin.
It's unclear why https://github.com/spacetelescope/romancal/pull/1085 added the upper pin.
This caused issues during testing with stasis as some packages use pytest > 8.0.
Regression tests all passed: https://github.com/spacetelescope/RegressionTests/actions/runs/10814310251
**Checklist**
- …

unpin pytest

---

.github/workflows/changelog.yml

Add a CI check to make sure PRs don't change `CHANGES.rst`. Changelog entries now take the form of towncrier fragments and manual edits to `CHANGES.rst` are no longer needed.
Here's a run of the new check that fails (due to an edit to `CHANGES.rst` added temporarily to this PR): https://github.com/spacetelescope/romancal/actions/runs/10906504272/job/30267904518?pr=1412
**Checklist**
- …

add CI check that CHANGES.rst is not modified

---

.github/workflows/changelog.yml

follow-on to #1412 to make the check less confusing
**Checklist**
- …

[CI] rename changelog check job to be more explicit on its purpose

---

.github/pull_request_template.md

analogous to https://github.com/spacetelescope/jwst/pull/8670
---------------
**Checklist**
- [N/A] ~updated relevant tests~
- [N/A] ~ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)~
---------------
- …

update pull request checklist

---

romancal/associations/association.py
romancal/associations/generate.py
romancal/associations/lib/log_config.py
romancal/flux/flux_step.py

I marked this PR as `no-changelog-entry-needed` as I don't believe it changes any public API.
The use of `MultilineLogger` is problematic as it causes all later created loggers to use this class (which is not 100% compatible with all logging usage). As the main thing it achieves is splitting log messages that contain newlines into multiple lines this PR also switches all log messages (that I was able to find) that contain a newline into multiple log messages. Note that since `MultilineLogger` is registered during an import it is unpredictable which loggers become instances of `MultilineLogger` (and which are the default `Logger`) so it's likely this PR introduces a small change in the log output for some modified log messages.
Although unknown at this point, `MultilneLogger` may be …

remove MultilineLogger, split logs with `\n` into multiple messages

---

changes/1436.outlier_detection.rst
romancal/outlier_detection/tests/test_outlier_detection.py
romancal/outlier_detection/utils.py

This is a follow-up to https://github.com/spacetelescope/romancal/pull/1357 to fix a but revealed during other testing.
Calling `OutlierDetection` with `on_disk=True` fails with:
```
NotImplementedError: cannot write Quantities to file.  Write array with q.value.tofile(...)
```
This PR works around the issue that calling `tofile` (which [stcal](https://github.com/spacetelescope/stcal/blob/787aa81a6719bb0c72be8972171c7f3f88c8adf0/src/stcal/outlier_detection/median.py#L214) now uses) is unsupported for Quantities.
This bug was hidden as the unit test that sets `in_memory=True` for outlier detection didn't provide an `on_disk` `ModelLibrary` which bypassed the call to `tofile` in stcal. This PR also updates the unit test to now check for that condition.
Regression tests all pass: …

Work around NotImplemented Quantity.tofile

---

changes/1446.general.rst
romancal/outlier_detection/tests/test_outlier_detection.py

This PR fixes testing so that files created by tests are removed after the test.
- …

Fix files left over by testing

---

romancal/regtest/test_wfi_grism_pipeline.py
romancal/regtest/test_wfi_image_pipeline.py

2 regression tests that may generate new truth files don't have `rtdata.output` set following: https://github.com/spacetelescope/romancal/pull/1426
This results in no file being available for 'okifying'. This PR sets `rtdata.output` for those 2 tests.
Regression tests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/11305239809
- …

add missing rtdata.output assignments to repointed tests

---

changes/1456.general.rst
romancal/regtest/conftest.py

Fixes #1454
This PR modifies the organization of okify results uploaded to artifactory to avoid overwriting results if multiple tests fail which share the same name (such as parameterized tests). To provide an example, if [test_rampfit_step](https://github.com/spacetelescope/romancal/blob/1945dad5eb600fe82acb865baf3f1d66da12dd7f/romancal/regtest/test_ramp_fitting.py#L165) is made to fail (by adding an `assert False`). 4 errors will be produced (from the 4 parametrizations of the test):
https://github.com/spacetelescope/RegressionTests/actions/runs/11325106885/job/31501401451#step:30:1020
as these 4 tests share the same name the results will be put into the same directory on artifactory "test_rampfit_step":
https://bytesalad.stsci.edu/ui/repos/tree/General/roman-pipeline-results/2024-10-14_ …

Put okify results in unique subdirectories to avoid file overwrites

---

docs/conf.py

remove `display_version` from docs config

---

.pre-commit-config.yaml
romancal/dark_current/tests/test_dark.py
romancal/linearity/tests/test_linearity.py
romancal/resample/tests/test_resample.py
romancal/tweakreg/tests/test_tweakreg.py

Closes #1141
This PR fixes the issues caught by pre commit in its automatic update, all of these are minor.
- …

Manual Pre-commit update

---

.github/workflows/contexts.yml
.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml
.github/workflows/tests_devdeps.yml

Similar to https://github.com/spacetelescope/jwst/pull/8869
It looks like the roman crds server was just updated to now require a second argument for the curl command leading to failures in the CI on main:
https://github.com/spacetelescope/romancal/actions/runs/11443462254/job/31836161436
This vendorizes the crds contexts workflow and fixes it for the recent change to the roman crds server.
- …

vendorize and fix crds workflow

---

changes/1471.associations.rst
docs/conf.py
docs/roman/associations/commands.rst
docs/roman/associations/skycell_asn.rst
pyproject.toml

Resolves [RCAL-936](https://jira.stsci.edu/browse/RCAL-936)
Closes #1458
This PR updates the read the docs to add information about the skycell_asn script to generate associations based on sky cells in the patch table from INS. 
The also updates the pyproject.toml file to install skycell_asn as script. 
- [N/A] update or add relevant tests
- [N/A] update relevant docstrings and / or `docs/` page
- [N/A] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
- ``changes/<PR#>.general.rst``: infrastructure or …

rcal-936 Update skycell_asn docs and add skycell_asn as a script at install time

---

changes/1448.outlier_detection.1.rst
changes/1448.resample.2.rst
changes/1448.tweakreg.0.rst
romancal/datamodels/library.py
romancal/outlier_detection/tests/test_outlier_detection.py
romancal/resample/tests/test_resample.py
romancal/tweakreg/tests/test_tweakreg.py

Group by `meta.observation.obs_id`.
Fixes: https://github.com/spacetelescope/romancal/issues/1259
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/11281421723
show 5 expected failures like the following:
```
{'values_changed': {"root['roman']['meta']['group_id']": {'new_value': '0000201001001001001011010001',
'old_value': 'roman0000211_1101_1'}}}
```
- …

Group models by obs_id for steps that use grouping

---

pyproject.toml
romancal/regtest/conftest.py
romancal/regtest/regtestdata.py
romancal/scripts/okify_regtests.py

https://github.com/spacetelescope/RegressionTests/pull/143
The `roman-pipeline-results/` repositories on Artifactory has lots of auto-generated run directories in the root, which clutters the file structure and makes it unwieldy to scroll through. This PR proposes moving the run directories from the root of the repository (`roman-pipeline-results/`) to a subdirectory (`roman-pipeline-results/regression-tests/runs/`):
```diff
- roman-pipeline-results/2024-09-25_GITHUB_CI_Linux-X64-py3.12-683/
+ roman-pipeline-results/regression-tests/runs/2024-09-25_GITHUB_CI_Linux-X64-py3.12-683/
```
- …

move run results directory on Artifactory to `regression-tests/runs/`

---

changes/1484.tweakreg.rst
romancal/tweakreg/tests/test_tweakreg.py
romancal/tweakreg/tweakreg_step.py

Resolves [RCAL-937](https://jira.stsci.edu/browse/RCAL-937)
Closes #1455 
This PR updates the `meta.wcsinfo.s_region` attribute after running `TweakRegStep`, which so far was only updating the WCS but not the footprint.
- https://github.com/spacetelescope/RegressionTests/actions/runs/11687286223
- …

RCAL-937: update s_region after running TweakRegStep.

---

changes/1498.resample.rst
romancal/regtest/test_mos_skycell_pipeline.py
romancal/resample/resample.py

Resolves [RCAL-935](https://jira.stsci.edu/browse/RCAL-935)
Closes #1432
This PR checks for correct skycell name in mosaic product and for resampled images using an association will add the target from the association the the location_name. 
- [N/A] update relevant docstrings and / or `docs/` page
Regression test is at https://github.com/spacetelescope/RegressionTests/actions/runs/11704297274 and the new results file shows that the location_name is updated so the the file will need okification
{'values_changed': {"root['roman']['meta']['basic']['location_name']": {'new_value': 'r274dp63x31y81',
'old_value': 'TBD'}}}
- …

rcal-935 Check for correct skycell name in mosaic product

---

changes/1493.general.rst
romancal/assign_wcs/utils.py
romancal/resample/resample.py

Resolves [RCAL-948](https://jira.stsci.edu/browse/RCAL-948)
Partially resolves #1466
This PR updates `romancal` to reduce duplicate code by using `stcal`'s `compute_s_region_keyword()`.
- https://github.com/spacetelescope/RegressionTests/actions/runs/11693055226
- …

Replace create_s_region with stcal's compute_s_region_keyword.

---

romancal/tweakreg/tests/test_astrometric_utils.py

Closes #1481
This PR reduces the number of supported formats to be tested in the unit test runs. It doesn't mean we're reducing the number of actual supported formats, which should be the same as those supported by `astropy`'s `table.Table` class (full list can be created by running `Table.write.list_formats()`).
All regtests are passing:
- https://github.com/spacetelescope/RegressionTests/actions/runs/11693029998
- …

Reduce the number of tests for supported catalog formats.

---

romancal/resample/resample.py

This PR fixes a bug when checking for the attribute "target" in model.asn.
Since `model.asn` is not a `dict` (it is an instance of the `MappingProxy` class), using`hasattr()` will not work because that object doesn't have attributes accessible via that function.
- https://github.com/spacetelescope/RegressionTests/actions/runs/11729059583
- …

Fix bug when checking for "target" in model.asn

---

changes/1503.source_detection.rst
romancal/lib/psf.py
romancal/lib/tests/test_psf.py
romancal/source_catalog/source_catalog.py
romancal/source_detection/source_detection_step.py

https://github.com/spacetelescope/romancal/pull/1494 uncovered a bug where building a psf messes up logging.
The call to `restart_logging`:
https://github.com/spacetelescope/romancal/blob/78d5e0f546b52e533e43b5739695d620717ce5df/romancal/lib/psf.py#L135
in `create_gridded_psf_model`
results in (if the [comment](https://github.com/spacetelescope/webbpsf/blob/3043186b5e420a87b6891bdac1380aec866068b6/webbpsf/utils.py#L62) is to be believed) webbpsf clearing all log handlers for the root logger:
https://github.com/spacetelescope/webbpsf/blob/3043186b5e420a87b6891bdac1380aec866068b6/webbpsf/utils.py#L54
This PR removes the call to `restart_logging` and the `logging_level` argument to `create_gridded_psf_model` (since I believe the logging infrastructure for webbpsf is by default …

remove logging manipulation during create_gridded_psf_model

---

changes/1512.source_catalog.rst
romancal/source_catalog/source_catalog.py

This PR restores flux units to the source catalog table.  The units were no longer included after a recent schema change.
- …

Restore flux units to source catalog table

---

romancal/source_catalog/source_catalog.py

This PR is a small followup/improvement to #1512. …

Improve unit handling

---

changes/1457.source_catalog.rst
romancal/source_catalog/source_catalog.py
romancal/source_catalog/source_catalog_step.py
romancal/source_catalog/tests/test_source_catalog.py

With this PR the input datamodel to the `source_catalog` step is copied before being operated on so that it is left completely unaltered.
- …

Copy input datamodel in source_catalog step

---

romancal/regtest/test_wfi_flat_field.py

Resolves [RCAL-952](https://jira.stsci.edu/browse/RCAL-952)
Closes #1516
This PR updates the input files for the grism flatfield test and checks that the output file matches the truth file
with flat_field set to "SKIPPED"
- …

rcal-952 Update grism flat field tests with correct input

---

changes/1527.general.rst
romancal/assign_wcs/assign_wcs_step.py
romancal/conftest.py
romancal/tweakreg/tests/test_astrometric_utils.py
romancal/tweakreg/tests/test_tweakreg.py

spacetelescope/gwcs#522 adds a warning to flag instances where bounding boxes that GWCS uses are ordered using the `C` (y, x) ordering rather than the `F` ordering the GWCS defaults to. GWCS handles the alternate ordering by default however tuple assignment to the forward transform before creating the GWCS causes astropy to assume a `C` ordering while if one assigns the same tuple directly to the wcs, GWCS will assume a `F` order. Due to this source of issues GWCS now throws a warning when it discovers an assigned bounding box with the `C` ordering as GWCS will always attach and handle bounding boxes specifically in the `F` ordering.
This PR updates `romancal` so that bounding boxes are always attached with the tuple correctly ordered and flagged as `F` order.
<details><summary>news …

Clean up bounding box assignment

---

.github/workflows/roman_ci.yml
.github/workflows/roman_ci_cron.yaml
changes/1543.general.rst
pyproject.toml

This PR bumps min python to 3.11 per [SPEC 0](https://scientific-python.org/specs/spec-0000/#support-window). `astropy` 7 has already made this bump. …

Bump min Python to 3.11 per SPEC 0

---

changes/1545.mosaic_pipeline.rst
romancal/pipeline/mosaic_pipeline.py

Closes #1544
This PR converts the `exit(0)` calls in the mosaic pipeline to exceptions.
Regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/12036561824
- …

turn exit calls into exceptions

---

changes/1538.associations.rst
changes/1538.scripts.rst
docs/roman/associations/asn_from_list.rst
docs/roman/associations/skycell_asn.rst
pyproject.toml
romancal/associations/asn_from_list.py
romancal/associations/skycell_asn.py
romancal/associations/tests/test_asn_from_list.py
romancal/associations/tests/test_skycell_asn.py
romancal/regtest/test_skycell_generation.py

This PR fixes the return code for `asn_from_list` and `skycell_asn` when they succeed (see #1535).
Which sorting out that fix I saw that:
- "schema_editor" and "schemadoc" are registered scripts that do not exist. This PR removes their registration from pyproject.toml
- The python function (not method) "skycell_asn" takes 1 argument "self". This PR updates the function signature to follow conventions of a non-method function. Further improvements are likely called for if this is expected to be part of the public API (it is mentioned in the documentation).
I left a number of in-line comments with some important ones about unused command line arguments for "skycell_asn" (which are not modified in this PR).
Closes https://github.com/spacetelescope/romancal/issues/1535
Regtests all pass: …

fix return code for asn_from_list and skycell_asn, remove unused scripts, cleanup skycell_asn

---

romancal/photom/tests/test_photom.py

When doing some testing in `roman_datamodels` I discovered a photom test that was not properly testing warnings causing issues. This PR refactors that test to use `pytest.warns` instead.
- …

Cleanup a photom test

---

romancal/pipeline/tests/test_exposure_pipeline.py

https://github.com/spacetelescope/romancal/pull/1525 introduced a use of the now deprecated `Pipeline.__call__`. This PR switches that use to `Pipeline.run`.
Regtests (to check for other `__call__` usage): https://github.com/spacetelescope/RegressionTests/actions/runs/12435096676/job/34720235255
all pass and show no warnings about deprecated `__call__` usage.
- …

switch `test_input_to_output` in `test_exposure_pipeline.py` to use run

---

romancal/resample/tests/test_resample.py

This PR fixes unit test failures that will occur if https://github.com/spacetelescope/stcal/pull/326 is accepted.
- …

Fix unit tests due to incoming changes in stcal

---

romancal/resample/tests/test_resample.py

This PR adjusts `crval` value in `test_populate_mosaic_basic_single_exposure` and `test_populate_mosaic_basic_different_observations` unit tests. The original value was 10 degrees off  due to which input images do not have any overlap with output image created with custom WCS parameters. With new changes in GWCS (enabling bounding box for inverse + a fix in stcal) this would lead to tests failing.
- …

Adjust crval in resample tests to get overlap with input

---

changes/1585.mosaic_pipeline.rst
romancal/pipeline/mosaic_pipeline.py
romancal/pipeline/tests/test_mosaic_pipeline.py
romancal/regtest/test_mos_pipeline.py
romancal/regtest/test_mos_skycell_pipeline.py
romancal/regtest/util.py
romancal/resample/resample.py
romancal/resample/tests/test_resample.py

Resolves [RCAL-930](https://jira.stsci.edu/browse/RCAL-930)
Closes #1431 
This PR addresses ensures that the L3 `meta.wcsinfo` can be used to accurately reproduce the originating WCS from which the wcsinfo block had been derived. In particular, when the L3 product has been created based on a skycell instead of the input images, this update ensures that roundtripping of the wcsinfo is still valid.
- …

RCAL-930 Roundtrip L3 wcsinfo especially when skycell specifications are used

---

changes/1613.scripts.rst
romancal/scripts/static_preview.py

Resolves [RCAL-958](https://jira.stsci.edu/browse/RCAL-958)
also allows `MosaicModel` when creating previews
```shell
roman_static_preview preview /grp/roman/ddavis/roman/level3_products/r00001_p_v01001001001_r274dp63x31y80_f158_coadd_i2d.asdf test.png 400 400
```
- …

allow `MosaicModel`

---

romancal/regtest/test_elp_tvac.py

This PR skips tweakreg and source_catalog steps for the tvac regtests.
Some tests are expected to fail based on https://github.com/spacetelescope/stcal/pull/326
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/13394507210/job/37410100713
show only expected failures.
- …

Disable tweakreg and source_catalog for tvac tests

---

docs/conf.py
docs/roman/source_catalog/psf.rst

Docs builds are failing because webbpsf docs now redirect to stpsf which is causing the webbpsf objects inventory fetch to fail (due to a redirect to the stpsf docs home).
This PR removes the single link to webbpsf docs in the romancal documentation and removes the intersphinx link. When this package is migrated to stpsf the link can be reestablished.
- …

remove webbpsf docs link

---

.github/workflows/data.yml

Follow up to https://github.com/spacetelescope/romancal/pull/1636 supporting https://github.com/spacetelescope/romancal/pull/1635
This PR updates `data.yml` to move the stpsf instead of webbpsf data to the expected cache path to fix the failure:
https://github.com/spacetelescope/romancal/actions/runs/13500040063
- …

fix data workflow to use stpsf

---

.github/workflows/roman_ci.yml
.github/workflows/tests_devdeps.yml
changes/1640.general.rst

Resolves [SCSB-195](https://jira.stsci.edu/browse/SCSB-195)
- …

test with latest supported Python version

---

changes/1644.outlier_detection.rst
changes/1644.resample.rst
docs/roman/outlier_detection/arguments.rst
docs/roman/outlier_detection/outlier_detection.rst
docs/roman/resample/arguments.rst
romancal/outlier_detection/outlier_detection_step.py
romancal/outlier_detection/utils.py
romancal/resample/resample_step.py

Closes #1630
This PR changes the default fillval in outlier detection and resample to `nan` (from `indef`).
The resample documentation was also updated removing the default values and instead (similar to the existing outlier detection documentation) the step spec is referred to at the top of the arguments page. This allows the defaults in the documentation to always be up to date with the step.
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/13638995662
show 3 expected differences all with absolute differences of 0 (since 0 values in truth files for resampled pixels with no contributed flux are now nan).
For example roman-pipeline-results/regression-tests/runs/2025-02-27_GITHUB_CI_Linux-X64-py3.11-1774/393_test_resample_single_file/mosaic_resamplestep.asdf …

change default fillval to nan

---

changes/1664.general.rst
romancal/regtest/benchmarks.py
romancal/regtest/conftest.py
romancal/regtest/resource_tracker.py
romancal/regtest/test_catalog.py
romancal/regtest/test_dark_current.py
romancal/regtest/test_linearity.py
romancal/regtest/test_mos_pipeline.py
romancal/regtest/test_mos_skycell_pipeline.py
romancal/regtest/test_multiband_catalog.py
romancal/regtest/test_ramp_fitting.py
romancal/regtest/test_refpix.py
romancal/regtest/test_resample.py
romancal/regtest/test_resource_tracker.py
romancal/regtest/test_tweakreg.py
romancal/regtest/test_wfi_dq_init.py
romancal/regtest/test_wfi_flat_field.py
romancal/regtest/test_wfi_grism_16resultants.py
romancal/regtest/test_wfi_grism_pipeline.py
romancal/regtest/test_wfi_image_16resultants.py
romancal/regtest/test_wfi_image_pipeline.py
romancal/regtest/test_wfi_photom.py
romancal/regtest/test_wfi_saturation.py

This PR adds test fixtures to make it easier for regtests to log peak memory usage and runtime (specifically of fixtures) to allow using regtests runs as pseudo benchmarks. The general API is:
```python
@pytest.fixture
def my_long_fixture(resource_tracker):
with resource_tracker.track():
pass
def test_log_tracked_resources(log_tracked_resources, my_long_fixture):
log_tracked_resources()
```
or for a test where the long-running or resource-intensive operation is in the test (not a fixture):
```python
def test_long_step(resource_tracker, request):
with resource_tracker.track(log=request):
pass
```
At the moment the `resource_tracker` fixture logs peak memory usage and runtime and reports these values in the `report*.xml` generated during regtests run (which is uploaded to github and …

add regtest resource tracking

---

romancal/conftest.py
romancal/regtest/conftest.py

I noticed the `diff_astropy_tables` and `mk_tmp_dirs` pytest fixtures were unused. This PR removes them.
Regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/14109377271
- …

Remove unused fixtures

---

changes/1671.source_catalog.rst
docs/roman/source_catalog/main.rst
romancal/source_catalog/source_catalog.py
romancal/source_catalog/tests/test_source_catalog.py

This PR changes the source catalog flux unit from uJy to nJy.
- …

Change source catalog flux unit from uJy to nJy

---

romancal/resample/resample.py

This PR updates the mean computation in the exposure time resampling during resample to use a float64 output (instead of the default float32). Once the new results are okified this should fix the nightly devdeps regtest runs which are failing due to numpy 2.3.0 changes that have small numerical differences for some operations: https://numpy.org/devdocs/release/2.3.0-notes.html#changes-to-the-main-iterator-and-potential-numerical-changes
Closes #1570
Fixes https://jira.stsci.edu/browse/RCAL-1007
Regtests running with devdeps: https://github.com/spacetelescope/RegressionTests/actions/runs/14197055170
Regtests running without devdeps: https://github.com/spacetelescope/RegressionTests/actions/runs/14200044661
Both runs show differences. Since this PR uses float64 for the mean result that's …

RCAL-1007: use float64 for total_exposure_time mean

---

changes/1675.source_catalog.rst
romancal/source_catalog/source_catalog.py
romancal/source_catalog/source_catalog_step.py

Update SourceCatalogStep to replace uses of `maker_utils` with non-test code.
Regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/14223844319
- …

remove maker_utils use in source_catalog

---

romancal/regtest/test_catalog.py

Fix the ordering of the catalog regtest test ids.
Closes #1679
Regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/14266199989
- …

fix test ids

---

changes/1678.multiband_catalog.rst
changes/1678.ramp_fitting.rst
changes/1678.skymatch.rst
romancal/multiband_catalog/multiband_catalog_step.py
romancal/ramp_fitting/ramp_fit_step.py
romancal/skymatch/skymatch_step.py

Remove `maker_util` usage in:
- MultibandCatalogStep
- RampFitStep
- SkymatchStep
Regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/14247918530
- …

Remove use of maker_utils in steps

---

pyproject.toml

since `pyarrow` is imported in `romancal`
- …

add `pyarrow` to explicit dependencies

---

changes/1688.resample.rst
romancal/resample/meta_blender.py
romancal/resample/tests/test_resample_step.py

This PR updates the resample "meta_blender" to build tables out of L2 metadata and insert them in the L3 "individual_image_meta" list. This was previously handled by `MosaicModel.append_individual_meta` which:
- crashes when `cal_logs` are provided
- crashes when a None value is provided
- crashes if the L2 metadata form each input image is not structured in the same way ("outlier_detection" missing from 1 L2 input will result in an exception)
There are a few cases to consider (with decisions made in this PR) that are caused by constructing tables of L2 metadata. These issues would not be present if instead the L2 metadata was copied as-is into the L3 metadata (and tables could be created via MosaicModel methods with user input about these decisions).
- What is the appropriate datatype …

remove uses of MosaicModel.append_individual_meta

---

changes/1663.resample.rst
romancal/resample/exptime_resampler.py
romancal/resample/resample.py

This PR updates the exposure time resampling to use `add_model_hook` added in https://github.com/spacetelescope/stcal/pull/342
This allows the exposure time resampling to reuse the pixmap computed for the data array resampling (improving the runtime of the resample step).
Regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/14622303294 show only unrelated failures that are also seen on main.
The resource tracking during regtests also shows an improvement in memory usage (resample single file show 4692MB on main and 4157MB with this PR).
- …

Update resample to use `add_model_hook`

---

changes/1715.outlier_detection.rst
romancal/outlier_detection/_fileio.py
romancal/outlier_detection/utils.py

Closes #1682
This PR switches the "save_intermediate_products" files optionally generated during outlier detection to use a "vanilla" asdf file containing the following:
- "data" either the resampled data array or the median array depending on the type of the intermediate product
- "wcs" the wcs of the intermediate product
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/14626199505
- …

save intermediate products as "vanilla" asdf files

---

romancal/scripts/make_regtestdata.sh

This PR updates the make_regtestdata.sh script to:
- fix the output directory for TVAC2_NOMOPS_WFIFLA_20240419194120_WFI01_cal and TVAC2_NOMOPS_WFIFLA_20240419194120_WFI01_dqinit
- stop when an error is encountered
- redirect stdout to both the log file and the console
Here is a successful run:
https://github.com/spacetelescope/RegressionTests/actions/runs/14600565199
containing console output:
https://github.com/spacetelescope/RegressionTests/actions/runs/14600565199/job/40962425115#step:28:67
and regtests running using the new files:
https://github.com/spacetelescope/RegressionTests/actions/runs/14603044387
showed 2 failures:
- romancal.regtest.test_source_catalog::test_forced_catalog
- romancal.regtest.test_multiband_catalog::test_multiband_catalog
I suspect these are from recent …

Fix make_regtestdata.sh output directory, stop on errors, redirect to log and console

---

romancal/assign_wcs/utils.py

Astropy has deprecated `isiterable`:
https://github.com/astropy/astropy/pull/18053
`np.iterable` is a drop-in replacement:
https://numpy.org/doc/1.23/reference/generated/numpy.iterable.html
This PR switches `isiterable` usage to `np.iterable`.
Regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/14710745764
- …

replace astropy isiterable with np.iterable

---

romancal/regtest/test_wfi_flat_field.py
romancal/scripts/make_regtestdata.sh
romancal/tests/dms_requirement_tests.json

This PR reorganizes the flat regtests so they can be okified once.
In addition to test shuffling this PR:
- remove the duplicate run of r0000101001001001001_0001_wfi01_f158_assignwcs.asdf
- removes the need for r0000101001001001001_0001_wfi01_f158_changetime_assignwcs.asdf (this is also removed from `make_regtest_data.sh` script)
Regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/14778335299
Regtest generator script running at: https://github.com/spacetelescope/RegressionTests/actions/runs/14778983273
Closes #1650
- …

RCAL-1031: allow flat regtests to be okified once

---

changes/1723.general.rst
docs/roman/stpipe/devel_logging.rst
romancal/lib/save_wcs.py
romancal/pipeline/exposure_pipeline.py
romancal/pipeline/mosaic_pipeline.py

Follow-up to https://github.com/spacetelescope/roman_datamodels/pull/506
This PR changes the calls to `getLogger()` to `getLogger(__name__)` to avoid changes to the root logger.
Regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/14759527893
show only failures related to the new crds context.
- …

use module specific loggers

---

changes/1731.source_catalog.rst
romancal/multiband_catalog/tests/test_multiband_catalog.py
romancal/source_catalog/aperture.py
romancal/source_catalog/psf.py
romancal/source_catalog/segment.py
romancal/source_catalog/source_catalog.py
romancal/source_catalog/tests/test_source_catalog.py

Resolves [RCAL-1061](https://jira.stsci.edu/browse/RCAL-1061)
Resolves [RCAL-1062](https://jira.stsci.edu/browse/RCAL-1062)
Closes #1729
Closes #1730
All of the columns listed in the `L4_Static_catalog_schema_v0.95.xlsx` document are now included, although some of them contain only placeholder values.
With this PR the (prompt) source catalog column names, dtypes, units, and descriptions are:
```
label                   int32        None            Label of the source segment in the segmentation image
flagged_spatial_index   int64        None            Spatial index bit flag encoding the projection, skycell, and pixel coordinate of the source
x_centroid              float32      pix             Column coordinate of the source centroid in the detection image from image moments (0 indexed) …
```

Update source catalog column units and add placeholder columns

---

romancal/source_catalog/source_catalog_step.py

This PR validates the result of `SourceCatalogStep` before returning to flush out any lazy loaded content that is referenced by the result that may not have been fully loaded. This is harmless (in that the model must be valid at this point anyway) but does result in duplicate validation. A follow-up PR will aim to remove this change by only copying the input if the input is a datamodel (not a filename) and copy only the required meta and data that is referenced from the input.
Regtests running: https://github.com/spacetelescope/RegressionTests/actions/runs/14890514503
- …

validate before returning result for `SourceCatalogStep`

---

changes/1785.ramp_fitting.rst
romancal/ramp_fitting/ramp_fit_step.py

This PR addresses a few failures in the devdeps due to existing rad changes. Here is the latest run showing several failures for ramp fitting due to a tag mismatch:
https://github.com/spacetelescope/RegressionTests/actions/runs/15430372053
This PR updates ramp fitting to copy the input nodes and strip their "read tags" to allow them to be saved with the newest tag versions.
Regtests with this PR: https://github.com/spacetelescope/RegressionTests/actions/runs/15443040145
show 1 failure for the elp run of tvac data:
```
{'dictionary_item_removed': ["root['roman']['meta']['cal_step']['jump']", "root['roman']['meta']['cal_step']['source_detection']"]}
```
showing that the output image model now no longer contains cal_step entries for the non-existent jump and source_detection steps.
I think …

strip read tags when ramp step constructs the output image model

---

changes/1767.source_catalog.rst
romancal/source_catalog/save_utils.py
romancal/source_catalog/source_catalog_step.py
romancal/source_catalog/tests/test_source_catalog.py

Resolves [RCAL-1082](https://jira.stsci.edu/browse/RCAL-1082)
Partially addresses #1765
Closes #1768 
This PR updates the SourceCatalogStep to handle the case where there are no valid pixels in the input image (e.g., all non-finite values or all pixels are masked).  For the issue reported in #1765, the coadd model input to `SourceCatalogStep` has NaN values in every pixel.
As part of this effort, I refactored all the save machinery into a separate function.
The current approach is that the step still saves the same files as usual, but these files are empty or contain all-zeros (segmentation image, and source catalog or input model). If desired, I can update this PR to not save files.
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/15146463903
CC: @schlafly …

Handle invalid input to the SourceCatalogStep

---

changes/1788.scripts.rst
docs/roman/pipeline_static_preview.rst
romancal/scripts/static_preview.py

This PR removes the dependence on Typer from the `roman_static_preview` script by using the builtin `argparse` instead. This change also reorders the order of CLI arguments so that the choice of subcommand `preview` or `thumbnail` goes AFTER the input and output paths:
```diff
- roman_static_preview preview [--no-compass] INPUT [OUTPUT] [SHAPE]...
+ roman_static_preview INPUT OUTPUT preview [--no-compass] SHAPE...
```
```diff
- roman_static_preview thumbnail [--compass] INPUT [OUTPUT] [SHAPE]...
+ roman_static_preview INPUT OUTPUT thumbnail [--compass] SHAPE...
```
examples of how real usages of `stpreview` change:
```diff
- roman_static_preview preview image.asdf image.png
+ roman_static_preview image.asdf image.png preview
- roman_static_preview thumbnail image.asdf image_thumb.png
+ …
```

[scripts] remove `typer` dependency from `roman_static_preview` by using builtin `argparse` instead, and reorder CLI arguments

---

changes/1805.docs.rst
docs/roman/stpipe/user_logging.rst

This PR cleans up the docs section pertaining to logging configuration removing descriptions of per-step configuration (which does not work: https://github.com/spacetelescope/stpipe/issues/241).
Link to updated page: https://roman-pipeline--1805.org.readthedocs.build/en/1805/roman/stpipe/user_logging.html
As this is only a docs change no regtests will be run.
xref: https://github.com/spacetelescope/jwst/pull/9565
- …

remove description of non-working logging configuration

---

romancal/regtest/test_ramp_fitting.py

This PR removes use of `stpipe.log.delegator` in the ramp fitting regtests and replaces it with a named logger. `stpipe.log.delegator` has issues (and is incompatible with python 3.13.4 and 3.13.5) and the logging usage here better fits a named logger.
Regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/15713445434
- …

remove use of stpipe log delegator

---

changes/1772.skycell.rst
romancal/skycell/match.py
romancal/skycell/plot.py
romancal/skycell/skymap.py
romancal/skycell/tests/test_skycell_match.py

Resolves [RCAL-1084](https://jira.stsci.edu/browse/RCAL-1084)
This PR addresses an issue referenced in https://github.com/spacetelescope/romancal/issues/1765, namely that the image footprint is not necessarily a rectangle with perfectly straight sides; rather, it may be distorted (modeled by the WCS).
- …

[RCAL-1084] include distortion when matching sky cells to image footprint

---

romancal/multiband_catalog/tests/test_multiband_catalog.py

Resolves [RCAL-1103](https://jira.stsci.edu/browse/RCAL-1103)
Closes #1826
This PR adds multiband catalog tests with PSF fitting.  This is not a fix, but adds tests to show the issue.  There were not any tests with PSF fitting enabled, which is why https://jira.stsci.edu/browse/RCAL-1103 was not noticed.
- …

Add multiband catalog tests with PSF fitting

---

changes/1823.source_catalog.rst
romancal/multiband_catalog/multiband_catalog_step.py
romancal/source_catalog/source_catalog.py
romancal/source_catalog/source_catalog_step.py

Resolves [RCAL-1102](https://jira.stsci.edu/browse/RCAL-1102)
Closes #1824
The ePSF files are not used unless PSF fitting is performed.
- …

Skip retrieval of ePSF reference file if fit_psf=False

---

romancal/conftest.py
romancal/regtest/test_multiband_catalog.py
romancal/regtest/test_ramp_fit_likelihood.py
romancal/regtest/test_ramp_fitting.py
romancal/regtest/test_resample.py
romancal/regtest/test_source_catalog.py
romancal/regtest/test_tweakreg.py
romancal/regtest/test_wfi_dq_init.py
romancal/regtest/test_wfi_photom.py

Add a `dms_logger` fixture for DMS requirement log messages. These go to stderr and are always outside of a normal step call (so these are lost with stpipe 0.9.0 and python 3.13.3/4 or with https://github.com/spacetelescope/stpipe/pull/240 which restricts the stpipe logging configuration to the duration of `Step.call`).
This PR restores those messages in a format that has the same log level, timestamp and message but differs in the logger name (similar to the other log messages with the stpipe fix).
For example, with stpipe 0.9.0 and python <3.13.3:
```
2025-07-03 09:51:44,489 - stpipe.TweakRegStep - INFO - DMS280 MSG: TweakReg step recorded as complete? : True
```
with stpipe 0.9.0 and python 3.13.3/4 no log message
with this PR and stpipe 0.9.0 (or with the linked stpipe PR) and any …

Add `dms_logger` fixture for logging `DMSXX` requirement log messages to stderr

---

changes/1843.resample.rst
romancal/lib/wcsinfo_to_wcs.py
romancal/regtest/util.py
romancal/resample/l3_wcs.py

This PR improves the accuracy with which the wcsinfo round trips in romancal.
romancal computes a bunch of information for the wcs.  One of these terms is the orientation, and another is the projection matrix.  The former is used directly in the WCS, while the latter contains the same information but is a slightly different computation (e.g., it can be computed as `np.degrees(np.arcsin(w.forward_transform.matrix_2.value[0, 1]))`.  In the new L3 metadata, Tyler proposes removing the rotation matrix and keeping only the orientation, so that the wcsinfo does not contain redundant information.  When making that change, the WCS began to fail a round-trip test.  This PR makes a few changes so that that round-trip test continues to pass.
As Brett & Nadia reported, this was only a roundoff error; …

Improve wcsinfo accuracy.

---

romancal/regtest/test_regtestdata.py

This RDM will begin setting the `meta.file_date` value to the current time upon file save, see spacetelescope/roman_datamodels#539. This means we should no longer check that as it will always be slightly different.
This PR purposefully excludes this information when running `compare_asdf`.
- …

Ignore the meta.file_date field when doing a comparison of asdf files

---

changes/1874.orientation.rst
romancal/orientation/set_telescope_pointing.py
romancal/orientation/tests/test_set_telescope_pointing.py

Resolves [RCAL-1121](https://jira.stsci.edu/browse/RCAL-1121)
This PR addresses issues found during initial implementation of the orientation scripts in the ground system environment
- …

RCAL-1121: Fix missing/mistaken meta assignments

---

changes/1862.source_catalog.rst
romancal/regtest/test_psf_library.py
romancal/regtest/test_tweakreg.py
romancal/tests/dms_requirement_tests.json

Resolves [RCAL-1108](https://jira.stsci.edu/browse/RCAL-1108)
Closes #1839
This PR adds the DMS identifier for the astrometry and ePSF tests as well as updating the tests. 
- [N/A] Do truth files need to be updated ("okified")?
Passing regression tests are at https://github.com/spacetelescope/RegressionTests/actions/runs/16496850855
- …

Rcal-1108 Add decorators for SOC requirements for the astrometry and ePSF regression tests

---

romancal/source_catalog/source_catalog.py
romancal/source_catalog/tests/test_source_catalog.py

We added new placeholder 'ra' and 'dec' columns to the catalogs.  These catalogs are the first things people will look at when trying to figure out what the ra/dec of a source is, and are intended to combine the various ras and decs that we provide into a single 'best' quantity.  We have not yet selected an approach for populating this 'best' quantity from the other ras and decs available, but I think it's good to at least populate this quantity with something so that most people's first plots do not have all of the sources colocated at (0, 0).
Regression test passing: https://github.com/spacetelescope/RegressionTests/actions/runs/16882974160 .
- …

Add default ra/dec.

---

changes/1911.source_catalog.rst
romancal/multiband_catalog/multiband_catalog_step.py
romancal/multiband_catalog/tests/test_multiband_catalog.py
romancal/source_catalog/aperture.py
romancal/source_catalog/source_catalog.py
romancal/source_catalog/source_catalog_step.py
romancal/source_catalog/tests/test_source_catalog.py
romancal/source_catalog/utils.py

…ile, save  those fractions in the table metadata, and update the is_extended property to use the ee_fraction values
Resolves [RCAL-1118](https://jira.stsci.edu/browse/RCAL-118)
Closes #
This PR reads the `ee_fractions` from the `apcorr` reference file and then computes the `ee_fractions` used by the pipeline. These values are then stored in the header of the `source_catalog` table.
- …

RCAL-1118 Record aperture corrections in catalog headers 

---

changes/1852.ramp_fitting.rst
romancal/ramp_fitting/ramp_fit_step.py

This PR is a downstream fix for spacetelescope/roman_datamodels#538.
- …

Resolve issue from roman_datamodels change

---

docs/roman/datamodels/models.rst

This PR includes the changes for `romancal` that are necessary to support spacetelescope/rad#688 and spacetelescope/roman_datamodels#555. The only change of note for `romancal` is that the `model.info()` output is very slightly different.
See https://github.com/spacetelescope/rad/pull/688#issue-3368635125 for an explanation of the failing regression tests.
- …

Follow on for the removal of tagged scalars from RAD

---

changes/1981.resample.rst
romancal/resample/meta_blender.py

This PR makes it possible for the `individual_image_meta` tables to be built when the internal tags are removed.
closes #1980
closes #1944
- …

Update meta_blender to use the schema pattern from RAD to build table

---

changes/1982.general.rst
docs/roman/datamodels/models.rst
romancal/stpipe/core.py

This PR represents the changes necessary in RCAL to support the removal of internal tags.
- …

Minor updates to support internal tag removal
